### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by aperezdom** [google/dagger#357]
In gradle we put the line:

compile 'com.clover.sdk:clover-android-sdk:27' 

in order to use mini Clover.

Clover works with API 19, Android 4.4.2  and our app  with  API 23.

We got error:

java.lang.NoClassDefFoundError: package.dagger.DaggerDaggerComponent
                                                                           at package.dagger.DaggerComponent$Initializer.init(DaggerComponent.java:76)

Without reference to Clover, our app works fine, but .

**Comment by ronshapiro** [comment]
This doesn't look like a Dagger error, it looks a build tools error. Try filing an issue with clover.
