### ISSUE TITLE
Explicitly specify generics for `Optional.absent()`

### ISSUE THREAD

**Issue by yogurtearl** [google/dagger#916]
I have some code that works in 2.11 but in 2.12 we get this error, using `-source 7`

```/app/build/generated/source/kapt/debug/com/example/dagger/DaggerMyComponent.java:43234: error: incompatible types:
   Optional<Object> cannot be converted to Optional<Thingy>
     MyActivity_MembersInjector.injectThingyOptional(instance, Optional.absent());
```

The gen'd code in Dagger should compile with source 7. 
In this case, I think it would be `Optional.<Thingy>absent()`

**Comment by davidliu** [comment]
A similar problem occurs for Optional.empty()

**Comment by ronshapiro** [comment]
Fixed in 
83459f2
