### ISSUE TITLE
[Hilt 2.42] [Kotlin 1.7.10] Failed to build

### ISSUE THREAD

**Issue by hoc081098** [google/dagger#3459]
```
> Task :app:kaptDebugKotlin

/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/local/UserLocalSourceImpl_Factory.java:10: error: package error does not exist
import error.NonExistentClass;
            ^
> Task :app:compileDebugJavaWithJavac FAILED
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/local/UserLocalSourceImpl_Factory.java:21: error: cannot find symbol
  private final Provider<DataStore<NonExistentClass>> dataStoreProvider;
                                   ^
  symbol:   class NonExistentClass
  location: class UserLocalSourceImpl_Factory
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/local/UserLocalSourceImpl_Factory.java:25: error: cannot find symbol
  public UserLocalSourceImpl_Factory(Provider<DataStore<NonExistentClass>> dataStoreProvider,
                                                        ^
  symbol:   class NonExistentClass
  location: class UserLocalSourceImpl_Factory
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/local/UserLocalSourceImpl_Factory.java:37: error: cannot find symbol
      Provider<DataStore<NonExistentClass>> dataStoreProvider,
                         ^
  symbol:   class NonExistentClass
  location: class UserLocalSourceImpl_Factory
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/local/UserLocalSourceImpl_Factory.java:42: error: cannot find symbol
  public static UserLocalSourceImpl newInstance(DataStore<NonExistentClass> dataStore,
                                                          ^
  symbol:   class NonExistentClass
  location: class UserLocalSourceImpl_Factory
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/DataModule_Companion_DataStoreFactory.java:12: error: package error does not exist
import error.NonExistentClass;
            ^
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/DataModule_Companion_DataStoreFactory.java:22: error: cannot find symbol
public final class DataModule_Companion_DataStoreFactory implements Factory<DataStore<NonExistentClass>> {
                                                                                      ^
  symbol: class NonExistentClass
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/DataModule_Companion_DataStoreFactory.java:25: error: cannot find symbol
  private final Provider<Serializer<NonExistentClass>> serializerProvider;
                                    ^
  symbol:   class NonExistentClass
  location: class DataModule_Companion_DataStoreFactory
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/DataModule_Companion_DataStoreFactory.java:28: error: cannot find symbol
      Provider<Serializer<NonExistentClass>> serializerProvider) {
                          ^
  symbol:   class NonExistentClass
  location: class DataModule_Companion_DataStoreFactory
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/DataModule_Companion_DataStoreFactory.java:34: error: cannot find symbol
  public DataStore<NonExistentClass> get() {
                   ^
  symbol:   class NonExistentClass
  location: class DataModule_Companion_DataStoreFactory
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/DataModule_Companion_DataStoreFactory.java:40: error: cannot find symbol
      Provider<Serializer<NonExistentClass>> serializerProvider) {
                          ^
  symbol:   class NonExistentClass
  location: class DataModule_Companion_DataStoreFactory
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/DataModule_Companion_DataStoreFactory.java:45: error: cannot find symbol
      Serializer<NonExistentClass> serializer) {
                 ^
  symbol:   class NonExistentClass
  location: class DataModule_Companion_DataStoreFactory
/home/runner/work/Refresh-Token-Sample/Refresh-Token-Sample/app/build/generated/source/kapt/debug/com/hoc081098/refreshtokensample/data/DataModule_Companion_DataStoreFactory.java:44: error: cannot find symbol
  public static DataStore<NonExistentClass> dataStore(Context applicationContext,
                          ^
  symbol:   class NonExistentClass
  location: class DataModule_Companion_DataStoreFactory
13 errors
```

- Build with koltin 1.6.10 or 1.6.21 works fine.

- I already tried adding 
```kotlin
kapt {
  correctErrorTypes = true
}
```
, but still no success.

---

- Full stacktrace: https://github.com/hoc081098/Refresh-Token-Sample/runs/7231374595?check_suite_focus=true
- Source code (build successfully with kotlin 1.6.21): https://github.com/hoc081098/Refresh-Token-Sample
- PR updates to Kotlin 1.7.x (failed to build): https://github.com/hoc081098/Refresh-Token-Sample/pull/149

**Comment by kuanyingchou** [comment]
This looks similar to this one: https://youtrack.jetbrains.com/issue/KT-52761/Kotlin-170-breaks-kapt-processing-for-protobuf-generated-java-sources

**Comment by kuanyingchou** [comment]
This should be for Kotlin Plugin or Protobuf Gradle Plugin. Closing this one.

**Comment by selim-akakce** [comment]
Actually just upgrade hilt version 2.42 and solved...

**Comment by simsekselim** [comment]
Actually just upgrade hilt version 2.42 and solved...

**Comment by Slion** [comment]
Similar issue here after upgrading to Kotlin 1.7.1. Upgrading from Hilt 2.40.1 to 2.44 fixed it. Not sure why Android Studio is not suggesting Hilt upgrades…

**Comment by hoc081098** [comment]
Just Update to kotlin 1.7.20, and it works
