### ISSUE TITLE
[Hilt] Dynamic Feature R8 isMinifyEnabled = true, showing error: is defined multiple times

### ISSUE THREAD

**Issue by mochadwi** [google/dagger#2102]
## Version
Hilt: 2.28.3-alpha in `:base` module
Using vanilla dagger in `:dynamic-feature` module
AGP: 4.0.1
GWP: 6.5.1
Kotlin: 1.3.72 

### Context
R8 isMinifyEnabled = false, succeed to build & runs, otherwise it fails as described in the title

### Question
1. Is it currently not supported to define same dependency class in multiple class and used injected across dynamic feature module?
1. Is it R8 restriction due to multiple class defined? and how to solve that?

### `:data` is a java only module

```
class MapperA @Inject constructor()

class AuthRepositoryImpl @Inject constructor(
    private val mapper: MapperA
) : AuthRepository

class AccountRepositoryImpl @Inject constructor(
    private val mapper: MapperA
) : AccountRepository
```

### `:dynamic-feature:auth` module

```
@DisableInstallInCheck
@Module
interface AuthModule {
    @get:[Binds]
    val AuthRepoistoryImpl.repository: AuthRepository
}
```

### `:dynamic-feature:account` module

```
@DisableInstallInCheck
@Module
interface AccountModule {
    @get:[Binds]
    val AccountRepoistoryImpl.repository: AccountRepository
}
```

I've tried to implement `@Qualifers` to annotate it as different dependencies but doesn't work either, see here #2074

**Comment by mochadwi** [comment]
I've also tried removing `kapt` in the `:dynamic-feature:*` `build.gradle` as stated in this [R8 discussion at stackoverflow](https://stackoverflow.com/a/63646833/3763032), instead `Unresolved reference` due to dagger unable to generate the class related to https://github.com/google/dagger/issues/955#issuecomment-609926321

**Comment by mochadwi** [comment]
After reading this: https://github.com/google/dagger/issues/261#issuecomment-160710763 Dagger/Hilt should generate the class based on the package name in this case different `:dynamic-feature:*` modules means different naming, but why in my case that the same class generated intsead? The reason R8 fails building it

**Comment by bcorso** [comment]
Hi @mochadwi, the title says "showing error: is defined multiple times". Is that the entire error message? If not can you post the entire error message here.

**Comment by mochadwi** [comment]
Okay, lemme reproduce it first

**Comment by mochadwi** [comment]
```
> Task :base-app:minifyStagingDebugWithR8 FAILED
/dynamic-features/auth/build/intermediates/module_and_runtime_deps_classes/stagingDebug/dynamic-feature-auth.jar: R8: Type company.data.mapper.MapperA_Factory is defined multiple times: /dynamic-features/auth/build/intermediates/module_and_runtime_deps_classes/stagingDebug/dynamic-features-auth.jar:company/data/mapper/MapperA_Factory.class, /dynamic-features/account/build/intermediates/module_and_runtime_deps_classes/stagingDebug/dynamic-feature-account.jar:company/data/mapper/MapperA_Factory.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':base-app:minifyStagingDebugWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete
```

Here's the error log @bcorso

**Comment by mochadwi** [comment]
when using `@Named` or `@Qualifier` approach, the result is same in this issue #2074

**Comment by Chang-Eric** [comment]
Since it is `MapperA_Factory` that is being duplicated, my guess as to what is going on here is that you aren't running the Dagger processor over the `MapperA` class and are pulling it into two different Dagger components.

Factory generation for `@Inject` classes can happen in two places: on the class itself if you run the Dagger processor (preferred) or lazily when used by the Dagger component. The problem with the second case is that if you have two Dagger components built separately we'll generate the same factory twice. (There's also a separate problem that generating it at the component can reduce build parallelism if you have a lot of factory classes to generate too, but that isn't your direct issue right now).

**Comment by mochadwi** [comment]
I see, so instead of using constructor `@Inject` in `:data` modules, I should've manually using `@Provides` in each `:dynamic-feature:auth` & `:dynamic-feature:account` in this case, to prevent duplication? cmiiw

**Comment by mochadwi** [comment]
What do you mean by **Dagger processor over the `MapperA`**, does it mean, I've to include `kapt` in `:data/build.gradle`? @Chang-Eric

**Comment by Chang-Eric** [comment]
Not just kapt, but the dependencies listed in here: https://dagger.dev/hilt/gradle-setup (assuming that is the right gradle module that contains the `MapperA` class)

**Comment by mochadwi** [comment]
Should I refactor my `:data/build.gradle` to use `com.android.library` to use `dagger-android`? @Chang-Eric

**Comment by mochadwi** [comment]
Awesome, this is works as expected thanks @Chang-Eric @bcorso 

But, does this steps missing in documentation? *or am I the one missing that, cmiiw

**Comment by Chang-Eric** [comment]
I don't think it is in the documentation (not sure there is a great place to put it right now), but you should have gotten a build warning about it at least https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/validation/InjectBindingRegistryImpl.java#L130

**Comment by mochadwi** [comment]
> I don't think it is in the documentation (not sure there is a great place to put it right now), but you should have gotten a build warning about it at least https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/validation/InjectBindingRegistryImpl.java#L130

Nice! Closing this issue now~
