### ISSUE TITLE
HiltModules is listed as a module, but is not annotated with @Module after update to 1.0.0-alpha03

### ISSUE THREAD

**Issue by i-disouki** [google/dagger#2357]
I built a sample project that using Hilt as a dependency injection lib with dynamic feature and it was working perfectly but after update to 1.0.0-alpha03 it is not working.
Here is the error log and link for the sample project [CurrencyConverter update_hilt branch](https://github.com/IbrahimDisouki/CurrencyConverter/tree/update_hilt)
`/home/ibrahim/Android/Projects/CurrencyConverter/home/build/tmp/kapt3/stubs/debug/com/ibrahim/home/HomeModule.java:7: error: com.ibrahim.home.HomeViewModel_HiltModules is listed as a module, but is not annotated with @Module
@dagger.Module(includes = {HomeViewModel_HiltModules.class, com.ibrahim.currencyconverter.di.FragmentViewModelModule.class, com.ibrahim.currencyconverter.di.AppModule.class})
^/home/ibrahim/Android/Projects/CurrencyConverter/home/build/tmp/kapt3/stubs/debug/com/ibrahim/home/HomeComponent.java:6: error: com.ibrahim.home.HomeModule has errors
@dagger.Component(dependencies = {com.ibrahim.currencyconverter.di.AppDependencies.class}, modules = {com.ibrahim.home.HomeModule.class})`
**Note that: I have do invalidate cashe, clean and rebuild and it didn't work.**

**Comment by Chang-Eric** [comment]
Hm, it looks like that is because you are directly including that generated code `HomeViewModel_HiltModules` in your src. https://github.com/IbrahimDisouki/CurrencyConverter/blob/update_hilt/home/src/main/java/com/ibrahim/home/HomeModule.kt#L14

That code is meant to be internal and uses `@InstallIn` for modules, so it probably changed between versions as just a part of development. Not sure why you want to install the modules directly, but it isn't something that is going to be stable.

**Comment by i-disouki** [comment]
Hi, @Chang-Eric I'm including `HomeViewModel_HiltModules` to be able to inject `HomeViewModel`.

**Comment by danysantiago** [comment]
@i-disouki, generated modules are not meant to be `included` with other hand-written modules, instead Hilt generates metadata for them so that they get included by the consuming app as long as they also use the Hilt compiler. This should occur normally in a multi-module project.

For using Hilt with dynamic feature modules, you might want to take a look at https://developer.android.com/training/dependency-injection/hilt-multi-module#dfm, where entry points are required due to the inverted dependency nature of feature modules.

**Comment by bcorso** [comment]
@i-disouki, I'm closing this out since @Chang-Eric and @danysantiago's comments should cover it. 

However, please feel free to continue the conversation if you're still having issues.

**Comment by i-disouki** [comment]
I have modified my project and it did not work. I asked a question on [stackoverflow](https://stackoverflow.com/q/66134976/3512164) Could you check it as it has more details about the issue.
