### ISSUE TITLE
[2.43 regression] error: cannot find symbol when using `@EntryPoint` to do injection

### ISSUE THREAD

**Issue by leinardi** [google/dagger#3487]
After updating from version 2.42 to 2.43 a compilation error is thrown:
```
> Task :app:hiltJavaCompileDebug FAILED
/home/rleinardi/Workspace/My/Forlago/app/build/generated/hilt/component_sources/debug/com/leinardi/forlago/DaggerForlago_HiltComponents_SingletonC.java:973: error: cannot find symbol
      injectDebugInitializer(arg0);
                             ^
  symbol:   variable arg0
  location: class SingletonCImpl
1 error

FAILURE: Build failed with an exception.
```

It happens in a class where an `@EntryPoint` it is used to inject some properties:
https://github.com/leinardi/Forlago/blob/426459ce39a3b1389e511cd5b1f9baaa529449d4/modules/feature-debug/src/main/kotlin/com/leinardi/forlago/feature/debug/initializer/DebugInitializer.kt#L36

A reproduction project is available here: https://github.com/leinardi/Forlago/tree/hilt

**Comment by ferinagy** [comment]
I can also confirm this with just plain dagger with no hilt. Pretty much all the injection methods inside generated `DaggerApplicationComponent` look like this:

```java
    @Override
    public void inject(BaseActivity activity) {
      injectBaseActivity(arg0);
    }
```
The `arg0` shows "Cannot resolve symbol" error.

**Comment by bcorso** [comment]
Closing, as this is a dupe of #3476.

Note that this issue should be fixed at head if you want to try the [HEAD-SNAPSHOTS](https://dagger.dev/dev-guide/versions#head-snapshot-setup). Otherwise, we should have a new minor release (2.43.1) out this week that includes the fix (just waiting on getting in a few other fixes before doing the release).
