### ISSUE TITLE
Generic field injection broke when updating from Dagger 2.11 to 2.12

### ISSUE THREAD

**Issue by vanniktech** [google/dagger#1390]
We're having a `DaggerMVPDialogFragment<VIEW extends MVPView, PRESENTER extends MVPPresenter<VIEW>>` with Dagger 2.11 (I know it's super old) we were able to `@Inject PRESENTER presenter;`. The relevant bits are:

```java
public abstract class DaggerMVPFragment<VIEW extends MVPView, PRESENTER extends MVPPresenter<VIEW>>
        extends Fragment implements BaseMVP<VIEW, PRESENTER>, HasSupportFragmentInjector {
    @Inject DispatchingAndroidInjector<Fragment> childFragmentInjector;
    @Inject PRESENTER presenter;
```

I'm in the process of upgrading to 2.20 and it does not seem like Dagger wants to inject our Presenter anymore. This is the error I'm getting at the app level when trying to build the component:

```
  required: DaggerMVPFragment<VIEW#1,PRESENTER#1>,PRESENTER#1
  found: NextbikeDetailFragment,Object
  reason: inference variable PRESENTER#1 has incompatible bounds
    equality constraints: NextbikeDetailPresenter
    lower bounds: Object
  where VIEW#1,PRESENTER#1,VIEW#2,PRESENTER#2 are type-variables:
    VIEW#1 extends MVPView declared in method <VIEW#1,PRESENTER#1>injectPresenter(DaggerMVPFragment<VIEW#1,PRESENTER#1>,PRESENTER#1)
    PRESENTER#1 extends MVPPresenter<VIEW#1> declared in method <VIEW#1,PRESENTER#1>injectPresenter(DaggerMVPFragment<VIEW#1,PRESENTER#1>,PRESENTER#1)
    VIEW#2 extends MVPView declared in class DaggerMVPFragment_MembersInjector
    PRESENTER#2 extends MVPPresenter<VIEW#2> declared in class DaggerMVPFragment_MembersInjector
/home/niklas/moovel/android-whitelabel-apps/flavor-kvv/build/generated/source/kapt/debug/com/moovel/kvv/injection/DaggerFlavoredComponent.java:9024: error: method injectPresenter in class DaggerMVPFragment_MembersInjector<VIEW#2,PRESENTER#2> cannot be applied to given types;
        DaggerMVPFragment_MembersInjector.injectPresenter(
```

Were we just lucky that this worked with 2.11 and broke with 2.12? These are the relevant bits from our NextbikeDetailFragment:

```java
public class NextbikeDetailFragment
        extends DaggerMVPFragment<NextbikeDetailView, NextbikeDetailPresenter>
```

`NextbikeDetailPresenter` is annotated with `@Inject` and has a `@FragmentScope` scope annotation that's correctly scoped and set up in our dependency graph.

I've also noticed that in the android library module that contains the `DaggerMVPFragment` the following method that is referenced in the trace above is generated inside `DaggerMVPFragment_MembersInjector.java`:

```java
public static <VIEW extends MVPView, PRESENTER extends MVPPresenter<VIEW>> void injectPresenter(
      DaggerMVPFragment<VIEW, PRESENTER> instance, PRESENTER presenter) {
    instance.presenter = presenter;
  }
```

However when I look at my `DaggerFlavoredComponent` on app level where the error is thrown and I use IntelliJ to navigate to the `DaggerMVPFragment_MembersInjector.java` the class that is shown here differs from the one being generated at the android library level. The one on app level is missing the `injectPresenter` function from above. I'm a bit at loss. Does anyone have some pointers?

I've also tried building on different machines and I'm 100% certain this is not a machine build related issue. I've tried all versions from 2.11 to 2.20 and only 2.11 was able to inject generics. Every other version is not capable of injecting generic fields.

**Comment by ronshapiro** [comment]
Your first code block is for `DaggerMVPActivity`, did you mean `DaggerMVPFragment`?

**Comment by vanniktech** [comment]
Ups yes. Updated it. We've got both and both are failing.

**Comment by ronshapiro** [comment]
We changed how we implemented members injection in 2.12, but that shouldn't intentionally make anything break. We strive to never generate code that doesn't compile; if Dagger doesn't allow it, we should give a better error why.

My best guess from looking at what you're doing (and seeing a similar error elsewhere recently) is that `MVPPresenter` is a `public` type, and `NextbikeDetailPresenter` is package private? If so, I have a better idea about what the error is and how to fix it

**Comment by vanniktech** [comment]
All of the following types are public:

- MVPPresenter
- MVPView
- DaggerMVPFragment
- NextbikeDetailPresenter
- NextbikeDetailFragment

So no, unfortunately, nothing is internal. They do however live in different packages.

**Comment by ronshapiro** [comment]
It's definitely weird that you'd be getting two different `_MembersInjector`s generated that are not equivalent... you don't happen to have different flavors of DaggerMVPFragment, do you?

Either way, the method is being resolved by javac... 

In `DaggerFlavoredComponent`, can you trace what the types of the arguments to `injectPresenter` are?

**Comment by vanniktech** [comment]
No. There's only one version of `DaggerMVPFragment`. 

Dagger generates the following:

```java
private final class NextbikeDetailFragmentSubcomponentImpl
    implements FragmentNextbikeModule_ProvideNextbikeDetailFragment
        .NextbikeDetailFragmentSubcomponent {
  @SuppressWarnings("rawtypes")
  private Provider nextbikeDetailPresenterProvider;

  private NextbikeDetailFragmentSubcomponentImpl(
      NextbikeDetailFragmentSubcomponentBuilder builder) {

    initialize(builder);
  }

  @SuppressWarnings("unchecked")
  private void initialize(final NextbikeDetailFragmentSubcomponentBuilder builder) {
    this.nextbikeDetailPresenterProvider =
        DoubleCheck.provider(
            NextbikeDetailPresenter_Factory.create(
                DaggerFlavoredComponent.this.provideNextbikeSDKProvider));
  }

  @Override
  public void inject(NextbikeDetailFragment arg0) {
    injectNextbikeDetailFragment(arg0);
  }

  private NextbikeDetailFragment injectNextbikeDetailFragment(NextbikeDetailFragment instance) {
    DaggerFragment_MembersInjector.injectChildFragmentInjector(
        instance,
        NextbikeBookingActivitySubcomponentImpl.this.getDispatchingAndroidInjectorOfFragment());
    DaggerMVPFragment_MembersInjector.injectPresenter(
        instance, nextbikeDetailPresenterProvider.get());
    return instance;
  }
}
```

`DaggerMVPFragment_MembersInjector` on app level looks like that:

```java
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package com.moovel.mvp;

import androidx.fragment.app.Fragment;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import javax.inject.Provider;

public final class DaggerMVPFragment_MembersInjector<VIEW extends MVPView, PRESENTER extends MVPPresenter<VIEW>> implements MembersInjector<DaggerMVPFragment<VIEW, PRESENTER>> {
    private final Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider;

    public DaggerMVPFragment_MembersInjector(Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider) {
        this.childFragmentInjectorProvider = childFragmentInjectorProvider;
    }

    public static <VIEW extends MVPView, PRESENTER extends MVPPresenter<VIEW>> MembersInjector<DaggerMVPFragment<VIEW, PRESENTER>> create(Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider) {
        return new DaggerMVPFragment_MembersInjector(childFragmentInjectorProvider);
    }

    public void injectMembers(DaggerMVPFragment<VIEW, PRESENTER> instance) {
        injectChildFragmentInjector(instance, (DispatchingAndroidInjector)this.childFragmentInjectorProvider.get());
    }

    public static <VIEW extends MVPView, PRESENTER extends MVPPresenter<VIEW>> void injectChildFragmentInjector(DaggerMVPFragment<VIEW, PRESENTER> instance, DispatchingAndroidInjector<Fragment> childFragmentInjector) {
        instance.childFragmentInjector = childFragmentInjector;
    }
}
```

Where the `injectPresenter` method is clearly missing. On library level (under `build/generated/source/apt/release/com/moovel/mvp/`) I get the following `DaggerMVPFragment_MembersInjector`:

```java
// Generated by Dagger (https://google.github.io/dagger).
package com.moovel.mvp;

import android.support.v4.app.Fragment;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.android.support.DaggerFragment_MembersInjector;
import javax.inject.Provider;

public final class DaggerMVPFragment_MembersInjector<
        VIEW extends MVPView, PRESENTER extends MVPPresenter<VIEW>>
    implements MembersInjector<DaggerMVPFragment<VIEW, PRESENTER>> {
  private final Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider;

  private final Provider<PRESENTER> presenterProvider;

  public DaggerMVPFragment_MembersInjector(
      Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider,
      Provider<PRESENTER> presenterProvider) {
    this.childFragmentInjectorProvider = childFragmentInjectorProvider;
    this.presenterProvider = presenterProvider;
  }

  public static <VIEW extends MVPView, PRESENTER extends MVPPresenter<VIEW>>
      MembersInjector<DaggerMVPFragment<VIEW, PRESENTER>> create(
          Provider<DispatchingAndroidInjector<Fragment>> childFragmentInjectorProvider,
          Provider<PRESENTER> presenterProvider) {
    return new DaggerMVPFragment_MembersInjector<VIEW, PRESENTER>(
        childFragmentInjectorProvider, presenterProvider);
  }

  @Override
  public void injectMembers(DaggerMVPFragment<VIEW, PRESENTER> instance) {
    DaggerFragment_MembersInjector.injectChildFragmentInjector(
        instance, childFragmentInjectorProvider.get());
    injectPresenter(instance, presenterProvider.get());
  }

  public static <VIEW extends MVPView, PRESENTER extends MVPPresenter<VIEW>> void injectPresenter(
      DaggerMVPFragment<VIEW, PRESENTER> instance, PRESENTER presenter) {
    instance.presenter = presenter;
  }
}
```

**Comment by ronshapiro** [comment]
I don't know what that decompiler view is, but that doesn't appear to be the issue. `NextbikeDetailPresenter` is using a rawtypes provider, which is indicating that it's not public and instead package-private. If that's not the case, perhaps there's a build system issue that's causing it to appear public in some cases and not in others.

**Comment by ronshapiro** [comment]
This is where we set it to be a rawtypes provider: https://github.com/google/dagger/blob/4612457b849d07a4702c5fcabb3b5811b9e527c0/java/dagger/internal/codegen/FrameworkFieldInitializer.java#L138

**Comment by vanniktech** [comment]
`NextbikeDetailPresenter` is in Kotlin and defined as `class NextbikeDetailPresenter @Inject constructor(` so it is public. I've noticed though that some of our Java Presenter classes weren't public and making them public ended up solving this entire riddle.

I believe Dagger didn't fully generate the `injectPresenter` method for the Kotlin classes since it failed on the Java classes not being public prior to the generation.

Is it possible to improve the error message in this case?

**Comment by ronshapiro** [comment]
I'm not sure this is a Dagger bug... I'd check the kapt stubs, but it looks like there's an issue where we're not receiving the right type information.

Again, I wouldn't trust whatever you're seeing in a decompiled view as authoritative. That's also not the issue - the compiler is seeing the method, it's just getting the wrong type information. We don't inspect that method when we call it either, we just trust that it's there. We would generate `injectPresenter` even if it was package private, as long as that `@Inject` field exists.

**Comment by vanniktech** [comment]
The Kotlin issue was resolved once I've made all of my Java Presenters public. They were package-private by default and I do think this is something Dagger where Dagger can provide a meaningful error message.

**Comment by vanniktech** [comment]
@ronshapiro would it make sense to provide a detailed error message when the generic class that wants to be injected isn't `public`? The missing `public` modifier caused all of the above mess and once I've added it to every Presenter that I've wanted to inject, Dagger compiled just fine.

**Comment by ronshapiro** [comment]
I don't know how we would detect that without contorting Dagger, and I'm not inclined to make a recommendation for something that we don't fully understand

**Comment by m-akopov** [comment]
@vanniktech You comment helped me a lot. I had 60+ presenters and 3 of them were not public - throwing the error on compilation. Spent 1 day finding out
