### ISSUE TITLE
Dagger 2.25 java.lang.NoClassDefFoundError: dagger/shaded/auto/common/BasicAnnotationProcessor

### ISSUE THREAD

**Issue by elye** [google/dagger#1642]
When compile the below code, all works fine in 2.24. However it error out as per title, when compile in 2.25

```
fun main() {
    val myClass = MyClass()
}

class MyClass {
    @Inject
    lateinit var stringMe: String

    init {
        DaggerMyComponent.create().subComponent().inject(this)
        println(stringMe)
    }
}

@Component
interface MyComponent {
    fun subComponent(): MySubcomponent
//    fun inject(a: MyClass)
}

@Subcomponent(modules = [MeSubModule::class])
interface MySubcomponent {
    fun inject(a: MyClass)
}

@Module
class MeSubModule {
    @Provides
    fun stringMe(): String = "Hi here"
}
```

**Comment by JakeWharton** [comment]
Dupe of #1639
