### ISSUE TITLE
Class keys into map don't work in Kotlin 1.3.30

### ISSUE THREAD

**Issue by consp1racy** [google/dagger#1478]
### Setup:
* AGP 3.3.x
* Dagger 2.21+
* Kotlin 1.3.30
* Gradle 5.3.1

### Error:
```
e: C:\gradle\build\DaggerKotlin\app\tmp\kapt3\stubs\debug\net\xpece\test\daggerkotlin\TheComponent.java:8: error: [Dagger/MissingBinding] java.util.Map<kotlin.reflect.KClass<? extends androidx.lifecycle.ViewModel>,javax.inject.Provider<androidx.lifecycle.ViewModel>> cannot be provided without an @Provides-annotated method.
public abstract interface TheComponent {
                ^
      java.util.Map<kotlin.reflect.KClass<? extends androidx.lifecycle.ViewModel>,javax.inject.Provider<androidx.lifecycle.ViewModel>> is injected at
          net.xpece.test.daggerkotlin.DaggerViewModelFactory(creators)
      net.xpece.test.daggerkotlin.DaggerViewModelFactory is injected at
          net.xpece.test.daggerkotlin.ViewModelModule.bindViewModelFactory(impl)
      androidx.lifecycle.ViewModelProvider.Factory is injected at
          net.xpece.test.daggerkotlin.MainActivity.vmf
      net.xpece.test.daggerkotlin.MainActivity is injected at
          net.xpece.test.daggerkotlin.TheComponent.inject(net.xpece.test.daggerkotlin.MainActivity)
```

### Current state:
Injecting a `Map<Class<out ViewModel>, @JvmSuppressWildcards Provider<ViewModel>>` based on `KClass<out ViewModel` keys produces an error.

Changing to `Map<KClass` ... doesn't help.

### Expected state:
Injecting a `Map<Class<out ViewModel>, @JvmSuppressWildcards Provider<ViewModel>>` based on `KClass<out ViewModel` keys should work as before.

### Workaround:
Migrate the class key annotation to Java.

### Relevant code:
```
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.PROPERTY_GETTER, AnnotationTarget.PROPERTY_SETTER)
@Retention(AnnotationRetention.RUNTIME)
@MapKey
annotation class ViewModelKey(val value: KClass<out ViewModel>)
```

```
@Singleton
class DaggerViewModelFactory @Inject constructor(
    private val creators: Map<Class<out ViewModel>, @JvmSuppressWildcards Provider<ViewModel>>
) : ViewModelProvider.Factory {
    // ...
}
```

```
@Module
abstract class ViewModelModule {

    @Binds
    abstract fun bindViewModelFactory(impl: DaggerViewModelFactory): ViewModelProvider.Factory

    @Binds
    @IntoMap
    @ViewModelKey(ViewModelOne::class)
    abstract fun bindViewModelOne(impl: ViewModelOne): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(ViewModelTwo::class)
    abstract fun bindViewModelTwo(impl: ViewModelTwo): ViewModel
}
```

```
@Component(modules = [ViewModelModule::class])
@Singleton
interface TheComponent {
    fun inject(activity: MainActivity)
}
```

```
class MainActivity : Activity() {

    protected val component by lazy {
        DaggerTheComponent.create()
    }

    @Inject
    protected lateinit var vmf: ViewModelProvider.Factory

    protected val vm1: ViewModelOne by lazy { vmf.create(ViewModelOne::class.java) }
    protected val vm2: ViewModelTwo by lazy { vmf.create(ViewModelTwo::class.java) }

    override fun onCreate(savedInstanceState: Bundle?) {
        component.inject(this)
        super.onCreate(savedInstanceState)
    }
}
```

### Sample
[DaggerKotlin.zip](https://github.com/google/dagger/files/3071959/DaggerKotlin.zip)

**Comment by NitroG42** [comment]
The issue probably comes from Kotlin as it is the Kotlin update that stopped the code for working.
I made a Kotlin issue just in case : https://youtrack.jetbrains.com/issue/KT-30979 (I was working on my own sample then saw your issue)

**Comment by VeegaP** [comment]
Would you mind expanding on the workaround with an example?

**Comment by bleeding182** [comment]
@VeegaP You switch the `ViewModelKey` from Kotlin to Java

```java
/**
 * Workaround in Java due to Dagger/Kotlin not playing well together as of now
 * https://github.com/google/dagger/issues/1478
 */
@MapKey
@Documented
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface ViewModelKey {
    Class<? extends ViewModel> value();
}
```

**Comment by VeegaP** [comment]
Thank you @bleeding182 :)

**Comment by william-reed** [comment]
Should be fixed in kotlin 1.3.31 (yet to be released) according to the kotlin issue linked above

**Comment by vladkarpman** [comment]
I still have the same issue. @bleeding182 Workaround doesn't work for me.

**Comment by consp1racy** [comment]
@vladkarpman post your error and your *exact* workaround code

**Comment by vladkarpman** [comment]
I am using workaround which was suggested @bleeding182.
It's simply class which is written on Java instead of Kotlin: 

_Dagger version_ = '2.22.1'
_Kotlin version_ = '1.3.30'

```
@MapKey
@Documented
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface ViewModelKey {
    Class<? extends ViewModel> value();
}
```
This is my `ViewModelFactory`:  
```
@Singleton
class ViewModelFactory @Inject constructor(
        private val viewModels: Map<Class<out ViewModel>, @JvmSuppressWildcards Provider<ViewModel>>) :
        ViewModelProvider.Factory {

    @Suppress("UNCHECKED_CAST")
    override fun <T : ViewModel?> create(modelClass: Class<T>): T {
        return viewModels[modelClass]?.get() as T
    }
}
```
Below is my `ViewModelModule` (nothing special) :

```
@Module
abstract class ViewModelModule {

    @Binds
    abstract fun bindViewModelFactory(viewModelFactory: ViewModelFactory): ViewModelProvider.Factory

    @Binds
    @IntoMap
    @ViewModelKey(DiscoverViewModel::class)
    abstract fun bindDiscoveryViewModel(discoverViewModel: DiscoverViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(LoginViewModel::class)
    abstract fun bindLoginViewModel(loginViewModel: LoginViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(OnBoardingViewModel::class)
    abstract fun bindOnBoardingViewModel(onBoardingViewModel: OnBoardingViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(ProfileViewModel::class)
    abstract fun bindProfileViewModel(profileViewModel: ProfileViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(ProfileCityViewModel::class)
    abstract fun bindProfileCityViewModel(profileCityViewModel: ProfileCityViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(ProfileDetailViewModel::class)
    abstract fun bindProfileDetailViewModel(profileDetailViewModel: ProfileDetailViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(ProfileLanguageViewModel::class)
    abstract fun bindProfileLanguageViewModel(profileLanguageViewModel: ProfileLanguageViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(MyQuestViewModel::class)
    abstract fun bindMyQuestViewModel(myQuestViewModel: MyQuestViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(TasksViewModel::class)
    abstract fun bindTasksViewModel(tasksViewModel: TasksViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(QuestDetailViewModel::class)
    abstract fun bindQuestDetailViewModel(questDetailViewModel: QuestDetailViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(QuestFinishViewModel::class)
    abstract fun bindQuestFinishViewModel(finishViewModel: QuestFinishViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(QuestsViewModel::class)
    abstract fun bindQuestsViewModel(questsViewModel: QuestsViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(MainViewModel::class)
    abstract fun bindMainViewModel(mainViewModel: MainViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(BuyPromoCodeViewModel::class)
    abstract fun bindBuyPromoCodeViewModel(buyPromoCodeViewModel: BuyPromoCodeViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(FactViewModel::class)
    abstract fun bindFactViewModel(factViewModel: FactViewModel): ViewModel
}
```

And this is error which i am facing: 

> /Users/vladislavkarpman/StudioProjects/StreetGames/app/build/tmp/kapt3/stubs/debug/com/streetgames/common/di/application/ApplicationComponent.java:8: error: [Dagger/MissingBinding] java.util.Map<java.lang.Class<? extends androidx.lifecycle.ViewModel>,javax.inject.Provider<androidx.lifecycle.ViewModel>> cannot be provided without an @Provides-annotated method.

**Comment by mikehc** [comment]
@vladkarpman list of things you need to check:
1. You don't have another file with `ViewModelKey` defined in a Kotlin file.
2. Make sure you are using the java annotations and not kotlin's. User this package: `import java.lang.annotation.*;`
3. As you are not posting the imports, just make sure everything else is using the Java version of `ViewModelKey`.

**Comment by vladkarpman** [comment]
@mikehc i checked everything from provided list, still the same error :(

**Comment by mikehc** [comment]
@vladkarpman post the rest of the other files, including imports. Maybe someone else has a better idea.

**Comment by DDihanov** [comment]
@vladkarpman switch back to the old Kotlin version until this gets fixed.

Which imports are you using in the factory class?

**Comment by vladkarpman** [comment]
@DDihanov added my imports

**Comment by DDihanov** [comment]
@vladkarpman Yup everything is fine on your end. I don't know why it keeps crashing. I "fixed" this issue by downgrading to `org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.20` and using the Kotlin ViewModelKey class.

**Comment by vladkarpman** [comment]
@DDihanov something went totally wrong, now if i even downgrade Kotling version, i still have this issue. Before everything just worked. Of course, I tried to clean project. 
Maybe it's because of new Android Studio, i am using 3.4...

**Comment by neworld** [comment]
Sometimes a build cache of kapt doesn't track deleted kotlin files. Probably you have to not only clean build dir but delete build cache as well.

**Comment by NitroG42** [comment]
Please try to run ./gradlew cleanBuildCache in your project, then remove your build folder, then try again.

**Comment by nicbell** [comment]
I can confirm, downgrading Kotlin fixes this..

**Comment by vladkarpman** [comment]
I just reset my branch to previous commit and now it works. 
I investigated a bit more and found out that cause of my issue was _gradle version 5.1.1_. 
Once i changed to 4.10.1, everything starts to work. 
Thanks guys for help.

**Comment by william-reed** [comment]
This is now fixed in kotlin 1.3.31 https://github.com/JetBrains/kotlin/blob/1.3.30/ChangeLog.md

**Comment by cbedoy** [comment]
I'm having the same issue on 

``` kotlin_version = '1.3.41' ```

**Comment by NezSpencer** [comment]
same

**Comment by sinadalvand** [comment]
> I'm having the same issue on
> 
> `kotlin_version = '1.3.41'`

same

**Comment by radeshf** [comment]
same in kotlin 1.3.50

**Comment by aldefy** [comment]
Facing this with 1.3.41 , will check with latest - x.50 and x.60 and see if it resolves

**Comment by react1ve** [comment]
@aldefy Same issue in x.50, x.60 and x.61

**Comment by aldefy** [comment]
what are you guys trying at the moment ? 
Do i write the provides func replacing abstract Binds ?

**Comment by Icyrockton** [comment]
1.3.70 same issue

**Comment by tatocaster** [comment]
1.3.71 same 🤔

**Comment by vincent-paing** [comment]
> ```java
> **
>  * Workaround in Java due to Dagger/Kotlin not playing well together as of now
>  * https://github.com/google/dagger/issues/1478
>  */
> ```

Do we need to change `DaggerViewModelFactory` too. I'm currently getting kapt issue with 1.3.71

```
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)
```

**Comment by vincent-paing** [comment]
Still happening with 1.3.71
Dagger 2.72
AGP 4.0-beta04
Gradle 6.1.1

Changing to java doesn't work. Why is this issue closed, it doesn't seem to be resolved yet

**Comment by consp1racy** [comment]
To anyone still complaining, care to provide a sample repro project? Thank you.

**Comment by SimonStefan** [comment]
I can confirm the Java workaround [1] works fine with
Dagger 2.21 && 2.27
Gradle 5.4.1 && 6.1.1 && 6.3
Kotlin 1.3.70 && 1.3.71

[1] https://github.com/google/dagger/issues/1478#issuecomment-485976409

**Comment by vincent-paing** [comment]
I clear my gradle cache and rerun and the java solution is working now

**Comment by felipezad** [comment]
I tried all of these and none of the above worked for me

dagger_version = ‘2.27'
kotlin_version = ‘1.3.72'
build:gradle:3.6.3'

**Comment by nikolaysmirnoff** [comment]
Обновление Добавление @JvmSuppressWildcardsисправило проблему. Код выглядит так:

private val providers: Map<Class<out ViewModel>, @JvmSuppressWildcards Provider<ViewModel>>

**Comment by nikolaysmirnoff** [comment]
https://github.com/google/dagger/issues/1540
Adding @JvmSuppressWildcards solved the problem.
private val providers: Map<Class<out ViewModel>, @JvmSuppressWildcards Provider<ViewModel>>

**Comment by hsm59** [comment]
Tried the solutions provided in this thread, yet facing the same issue.

dagger = 2.15
kotiln version = 1.3.72
build.gradle = 4.0.1

**Comment by anshul-gmp** [comment]
ext.kotlin_version = "1.4.0"
    ext.daggerVersion = '2.25.4'
    build.gradle = "4.0.1"

Still facing the issue. Anyone found any solution ?
