### ISSUE TITLE
Cannot find symbol @Generated after 2.35

### ISSUE THREAD

**Issue by tinder-inakivillar** [google/dagger#2588]
Hi, since the update 2.35.x we have started to see builds failing with `cannot find symbol @Generated` in kapt modules. Analyzing the inputs of the tasks for a given module we observed the same hash entry for module:kaptKotlin inputs but different for module:compileKotlin inputs. The differences are in the source input of the compileKotlin task:
Wrong
```
@DaggerGenerated
@Generated(
   value = "dagger.internal.codegen.ComponentProcessor",
   comments = "https://dagger.dev"
)
@SuppressWarnings({
   "unchecked",
})
```
Correct
```
@DaggerGenerated
@SuppressWarnings({
   "unchecked",
   "rawtypes"
})
```
Rerunning the tasks locally fixes the problem. KGP/AGP/Gradle versions didn't change in the project. I have checked previous issues and workarounds like https://github.com/google/dagger/issues/1449#issuecomment-495404186 but do you have more info on this issue in recent 2.35 versions?

**Comment by bcorso** [comment]
> Hi, since the update 2.35.x we have started to see builds failing with cannot find symbol @Generated in kapt modules.

What was the last Dagger version that works for you? E.g. does Dagger 2.34.x work for you?

> Rerunning the tasks locally fixes the problem. KGP/AGP/Gradle versions didn't change in the project.

Just to add a bit more details to how it works under the hood -- [internally](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/base/SourceFileGenerator.java#L96) Dagger relies on auto-common's [GeneratedAnnotations.java](https://github.com/google/auto/blob/master/common/src/main/java/com/google/auto/common/GeneratedAnnotations.java#L54), which should only add the `@Generated` annotation if `Generated.class` is available in the class path. So theoretically the `cannot find symbol @Generated` should never happen. Not sure yet what's going on here to make this fail.

**Comment by tinder-inakivillar** [comment]
Hi, thanks for the answer and for pointing the internals of generated annotations.
I checked in the build history and we started seeing this problem before the update. It's true that after the update to 2.35 the problem has been reproduced actively. 
I'm not sure if is a Dagger issue, closing the issue.
