### ISSUE TITLE
Support for Kotlin 1.5.20

### ISSUE THREAD

**Issue by Jeff11** [google/dagger#2684]
With Kotlin 1.5.20-RC I get this error.

Works with Kotlin 1.5.10.

Dagger version 2.37

```
/Users/username/projects/myproject/appname/build/tmp/kapt3/stubs/devAppnameDebug/de/company/appname/ApplicationMain.java:47: error: [Hilt]
public final class ApplicationMain extends company.appname.ApplicationBase {
             ^
  Expected @HiltAndroidApp to have a value. Did you forget to apply the Gradle Plugin? (dagger.hilt.android.plugin)
  See https://dagger.dev/hilt/gradle-setup.html
  [Hilt] Processing did not complete. See error above for details.
```
```
/Users/username/projects/myproject/appname/build/tmp/kapt3/stubs/devAppnameDebug/de/company/appname/ui/SecondFragment.java:43: error: [Hilt]
public final class SecondFragment extends company.appname.ui.base.BaseFragment {
             ^
  Expected @AndroidEntryPoint to have a value. Did you forget to apply the Gradle Plugin? (dagger.hilt.android.plugin)
  See https://dagger.dev/hilt/gradle-setup.html
  [Hilt] Processing did not complete. See error above for details.
```

**Comment by bcorso** [comment]
Did you forget to apply the [Gradle Plugin (dagger.hilt.android.plugin)](https://dagger.dev/hilt/gradle-setup#hilt-gradle-plugin)?

**Comment by Jeff11** [comment]
Yes, I have. Until Kotlin 1.5.10 there are no problems with the build. It just started with 1.5.20-M1 and -RC.

I can switch to 1.5.10 and the build will work.

**Comment by burhankhanzada** [comment]
i also have this issue and @jeff11 is rith its working fine with 1.5.10

**Comment by SteinerOk** [comment]
Also with 1.5.20-RC not working compiler argument for disabling InstallIn check:
```
        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "dagger.hilt.disableModulesHaveInstallInCheck": "true"
                ]
            }
        }
```

**Comment by bcorso** [comment]
This sounds like a bug in the kotlin/kapt plugin rather than Hilt. In particular, `javaCompilerOptions.annotationProcessorOptions` are just getting ignored in general, as mentioned in https://github.com/google/dagger/issues/2684#issuecomment-860175674. This ends up causing Hilt to fail because the Hilt Gradle plugin sets these options in [HiltGradlePlugin.kt](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/plugin/src/main/kotlin/dagger/hilt/android/plugin/HiltGradlePlugin.kt#L430).

FWIW, it looks like the processing options set through `kapt.javacOptions` do still work, so as a workaround you can set the options manually:

```groovy
kapt {
    javacOptions {
        // These options are normally set automatically via the Hilt Gradle plugin, but we
        // set them manually to workaround a bug in the Kotlin 1.5.20
        option("-Adagger.fastInit=ENABLED")
        option("-Adagger.hilt.android.internal.disableAndroidSuperclassValidation=true")
    }
}
```

**Comment by slavonnet** [comment]
kapt.use.worker.api=false
fixes many strange issues from kapt

**Comment by bcorso** [comment]
I've filed a bug with kotlin here: https://youtrack.jetbrains.com/issue/KT-47416

**Comment by SerggioC** [comment]
> kapt.use.worker.api=false
> fixes many strange issues from kapt

It'll decrease build speed though:
https://kotlinlang.org/docs/kapt.html#improving-the-speed-of-builds-that-use-kapt

> To improve the speed of builds that use kapt, you can enable the Gradle worker API for kapt tasks. Using the worker API lets Gradle run independent annotation processing tasks from a single project in parallel, which in some cases significantly decreases the execution time.

@bcorso sulution works. 👍

**Comment by mmathieum** [comment]
Kotlin 1.5.21 fixes the issue for me
https://github.com/JetBrains/kotlin/releases/tag/v1.5.21

**Comment by yunus1202** [comment]
adx<a
