### ISSUE TITLE
Support for Android JetPack? 

### ISSUE THREAD

**Issue by abredykhin** [google/dagger#1175]
After trying alpha version of jet pack i get compiler errors for DaggerFragment and similar components. That's because fragments are now in the androidx package. 

Is there a plan how to add support for this? I guess for now I can just copy/paste code for DaggerFragment and DaggerActivity into my own base class

**Comment by JakeWharton** [comment]
Your build is configured incorrectly. The dejetifier should run and rewrite the bytecode of the fragment library into the old package.

While Dagger should update eventually, this isn't a blocking issue as it's exactly what dejetifier was built to solve.

**Comment by abredykhin** [comment]
Can you suggest what to look for? It's a very simple project with just 3 fragments and 3 basic dagger modules for them. I used the 'Refactor to AndroidX' in AS. After deleting the build folder and doing clean/build I get compilation error in the generated apt code. Here's the original module: 

`
@Module
public abstract class CityModule {

    @FragmentScoped
    @ContributesAndroidInjector
    abstract CityListFragment cityListFragment(); //provide injector for the fragment

    @Provides
    static ViewModelFactory provideViewModelFactory(VenueRepo venueRepo) {
        return new ViewModelFactory(venueRepo); // inject repository into ViewModel
    }

}
`
And the generated one: 
`
@Module(subcomponents = CityModule_CityListFragment.CityListFragmentSubcomponent.class)
public abstract class CityModule_CityListFragment {
  private CityModule_CityListFragment() {}

  @Binds
  @IntoMap
  @FragmentKey(CityListFragment.class)
  abstract AndroidInjector.Factory<? extends Fragment> bindAndroidInjectorFactory(
      CityListFragmentSubcomponent.Builder builder);

  @Subcomponent
  @FragmentScoped
  public interface CityListFragmentSubcomponent extends AndroidInjector<CityListFragment> {
    @Subcomponent.Builder
    abstract class Builder extends AndroidInjector.Builder<CityListFragment> {}
  }
}
`

The error I see is (@FragmentKey annotation is highlighted in red)
> error: incompatible types: Class<CityListFragment> cannot be converted to Class<? extends Fragment>

where CityListFragment extends BaseFragment and that class extends DaggerFragment

**Comment by ronshapiro** [comment]
Are you on v2.16? I fixed a bug for jetifier to work, so if you're on an earlier version, it won't work properly. Upgrade and you should be set :)

**Comment by aouerfelli** [comment]
The `dagger-android` module seems to be listed as one of the known libraries that aren't compatible with the refactor yet (see [here](https://developer.android.com/topic/libraries/support-library/androidx-rn#1.0.0a1-ki)). Was this fixed in 2.16?

**Comment by abredykhin** [comment]
I was using 2.15. After updating to 2.16 I now see different error when building the project: 

> java.lang.RuntimeException: java.lang.StackOverflowError
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.IncrementalAnnotationProcessingCompileTask.call(IncrementalAnnotationProcessingCompileTask.java:73)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringDecorator.execute(IncrementalResultStoringDecorator.java:41)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringDecorator.execute(IncrementalResultStoringDecorator.java:27)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalAnnotationProcessingCompiler.execute(IncrementalAnnotationProcessingCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalAnnotationProcessingCompiler.execute(IncrementalAnnotationProcessingCompiler.java:36)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:156)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:126)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StackOverflowError
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:306)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:303)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:303)
	at com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation(AnnotationProxyMaker.java:87)
	at com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation(AnnotationProxyMaker.java:79)
	at com.sun.tools.javac.code.AnnoConstruct.getAnnotation(AnnoConstruct.java:179)
	at dagger.internal.codegen.MapKeys.unwrapValue(MapKeys.java:85)
	at dagger.internal.codegen.MapKeys.mapKeyType(MapKeys.java:94)
	at dagger.internal.codegen.KeyFactory.bindingMethodKeyType(KeyFactory.java:225)
	at dagger.internal.codegen.KeyFactory.forBindingMethod(KeyFactory.java:182)
	at dagger.internal.codegen.KeyFactory.forBindsMethod(KeyFactory.java:148)
	at dagger.internal.codegen.DelegateDeclaration$Factory.create(DelegateDeclaration.java:75)
	at dagger.internal.codegen.ModuleDescriptor$Factory.create(ModuleDescriptor.java:180)
	at dagger.internal.codegen.ComponentDescriptor$Factory.addTransitiveModules(ComponentDescriptor.java:735)...

**Comment by ronshapiro** [comment]
@aouerfelli I just sent a change to update that text. 2.16 should work.

@abredykhin Does 2.16 work for you _without_ jetifier? Let's try to isolate this issue. That stack trace is bizarre

**Comment by abredykhin** [comment]
No I get the same StackOverflowError, with or without jetifier. Tried nuking the build folder and do clean/build - no success. I can attach zip of source code here, will it help? It's a very simple project.

**Comment by ronshapiro** [comment]
A github repository would be great. 

Probably the issue is that you have a component cycle. But it's hard to tell without looking.

**Comment by abredykhin** [comment]
I don't have component cycles in my code. But surprisingly after restarting AS now build passes, probably error was caused by something in cache

**Comment by ronshapiro** [comment]
@homandiy there's `dagger.android.support.FragmentKey`
