### ISSUE TITLE
Hilt 2.59: ComponentTreeDeps annotation missing from runtime artifacts - compilation fails with AGP 9.0

### ISSUE THREAD

**Issue by paragbaxi** [google/dagger#5099]
After upgrading to Hilt 2.59 with AGP 9.0.0, the build fails because the Hilt Gradle plugin generates code referencing  dagger.hilt.internal.componenttreedeps.ComponentTreeDeps, but this class does not exist in any Hilt 2.59 runtime artifact.

  Environment

  - Hilt version: 2.59
  - AGP version: 9.0.0
  - Gradle version: 9.3.0
  - Kotlin version: 2.2.10
  - KSP version: 2.2.10-2.0.2
  - OS: macOS (also reproducible on Linux CI)

  Steps to Reproduce

  1. Configure project with AGP 9.0.0 and Hilt 2.59:
  // build.gradle.kts
  plugins {
      id("com.google.dagger.hilt.android") version "2.59"
  }
  2. Run a clean build:
  ./gradlew clean assembleDebug

  Expected Behavior

  Build succeeds - generated Hilt code compiles against Hilt runtime.

  Actual Behavior

  Compilation fails with:

  error: package dagger.hilt.internal.componenttreedeps does not exist
  import dagger.hilt.internal.componenttreedeps.ComponentTreeDeps;
                                                ^

  error: cannot find symbol
  @ComponentTreeDeps(
   ^
    symbol: class ComponentTreeDeps

  Investigation

  I verified the class is missing from all Hilt 2.59 artifacts:

  # Search all Dagger 2.59 JARs in Gradle cache
  find ~/.gradle/caches -name "*.jar" -path "*dagger*" -path "*2.59*" -exec jar tf {} \; | grep -i componenttree
  # No results

  # Confirm the annotation doesn't exist
  find ~/.gradle/caches -name "*.jar" -path "*hilt*" -path "*2.59*" -exec jar tf {} \; | grep componenttreedeps
  # No results

  The Hilt Gradle plugin generates code that imports dagger.hilt.internal.componenttreedeps.ComponentTreeDeps, but this package/class does not exist in:
  - hilt-android-2.59.jar
  - hilt-core-2.59.jar
  - hilt-android-compiler-2.59.jar
  - Any other Dagger 2.59 artifact

  Workaround

  Downgrade to Hilt 2.58. Despite not officially supporting AGP 9.0, it builds and runs correctly:

  // gradle/libs.versions.toml
  googleDaggerHilt = "2.58"  # Works with AGP 9.0

  Root Cause Hypothesis

  It appears the 2.59 release included the Gradle plugin changes for AGP 9.0 support (which generate ComponentTreeDeps references) but the corresponding runtime annotation class was not included in the published artifacts.

**Comment by paragbaxi** [comment]
## Additional Investigation: Multiple Missing Annotations

We attempted a polyfill workaround by creating stub annotation classes. This revealed that **multiple internal annotations are missing**, not just `ComponentTreeDeps`:

### Missing Annotations Discovered

| Package | Class |
|---------|-------|
| `dagger.hilt.internal.componenttreedeps` | `ComponentTreeDeps` |
| `dagger.hilt.internal.processedrootsentinel` | `ProcessedRootSentinel` |
| `dagger.hilt.internal.aggregatedroot` | `AggregatedRoot` |

### Processor Expects Undocumented Properties

Even after creating stub annotations matching the generated code, the annotation processor expects **additional properties** not used in the generated code:

```
error: [Hilt] No property named aliasOfDeps was found in annotation ComponentTreeDeps
error: [Hilt] No property named uninstallModulesDeps was found in annotation ComponentTreeDeps
error: [Hilt] No property named earlyEntryPointDeps was found in annotation ComponentTreeDeps
error: [Hilt] No property named root was found in annotation AggregatedRoot
```

### Verification

```bash
# What exists in hilt-core-2.59.jar under dagger/hilt/internal/:
jar tf hilt-core-2.59.jar | grep 'dagger/hilt/internal/'

# Results - these exist:
dagger/hilt/internal/GeneratedComponent.class
dagger/hilt/internal/GeneratedComponentManager.class
dagger/hilt/internal/GeneratedComponentManagerHolder.class
dagger/hilt/internal/Preconditions.class
dagger/hilt/internal/UnsafeCasts.class

# But NO: componenttreedeps/, processedrootsentinel/, aggregatedroot/
```

### Conclusion

The polyfill approach is not viable because:
1. Multiple annotation classes are missing (not just one)
2. The processor expects properties beyond what the generated code uses
3. The full schema of required annotations is unknown

**Workaround confirmed**: Hilt 2.58 works with AGP 9.0 despite not officially supporting it.

**Comment by bcorso** [comment]
> # Confirm the annotation doesn't exist
> find ~/.gradle/caches -name "*.jar" -path "hilt" -path "2.59" -exec jar tf {} ; | grep componenttreedeps

I think the issue with the above analysis is that the `hilt-android` artifact is an `aar` not a `jar file (https://repo1.maven.org/maven2/com/google/dagger/hilt-android/2.59/).

If you unzip the `aar` and look within `classes.jar` you should find the `ComponentTreeDeps` class:

```
$ jar tf hilt-android-2.59/classes.jar | grep ComponentTreeDeps
dagger/hilt/internal/componenttreedeps/ComponentTreeDeps.class
```

That said, I'm not really sure what's going on with your setup and why it behaves differently between 2.58 to 2.59. If you get any more information feel free to post here.

**Comment by paragbaxi** [comment]
**Investigation Update: `hiltJavaCompile` Task Classpath Issue**

Following up on @bcorso's insight - you're correct that the annotations ARE present in `hilt-android.aar/classes.jar`:

```bash
$ jar tf hilt-android-2.59/classes.jar | grep ComponentTreeDeps
dagger/hilt/internal/componenttreedeps/ComponentTreeDeps.class

$ jar tf hilt-android-2.59/classes.jar | grep ProcessedRootSentinel  
dagger/hilt/internal/processedrootsentinel/ProcessedRootSentinel.class
```

**Root Cause Identified**

The issue is in the Hilt Gradle plugin's `hiltJavaCompile{Variant}` task. This task compiles the generated `*_ComponentTreeDeps.java` files but its classpath does not include the classes from `hilt-android.aar`.

**Generated Code That Fails**

The plugin generates code at `build/generated/hilt/component_trees/{variant}/`:

```java
// MyApplication_ComponentTreeDeps.java
package com.example.application;

import dagger.hilt.internal.componenttreedeps.ComponentTreeDeps;  // Line 4 - fails
// ...
@ComponentTreeDeps(  // Line 45 - fails
    rootDeps = { ... },
    // ...
)
public class MyApplication_ComponentTreeDeps {
}
```

```java
// _com_example_application_MyApplication.java  
import dagger.hilt.internal.processedrootsentinel.ProcessedRootSentinel;  // fails

@ProcessedRootSentinel(  // fails
    roots = "com.example.application.MyApplication"
)
```

**Dependency Resolution Analysis**

```bash
# hilt-android IS on the main compile classpath
$ ./gradlew :app:dependencies --configuration freeDebugCompileClasspath | grep hilt-android
+--- com.google.dagger:hilt-android:2.59

# hilt-android IS on the annotation processor classpath  
$ ./gradlew :app:dependencies --configuration hiltAnnotationProcessorFreeDebug | grep hilt-android
\--- com.google.dagger:hilt-android:2.59

# BUT hiltCompileOnly is EMPTY by default
$ ./gradlew :app:dependencies --configuration hiltCompileOnlyFreeDebug
hiltCompileOnlyFreeDebug - Hilt aggregated compile only dependencies for 'freeDebug'
No dependencies
```

Even after manually adding `hilt-android` to `hiltCompileOnly*`:

```kotlin
// build.gradle.kts
configurations.matching { it.name.startsWith("hiltCompileOnly") }.configureEach {
    dependencies {
        add(this@configureEach.name, libs.google.dagger.hilt)
    }
}
```

The dependency shows up in the configuration but `hiltJavaCompileFreeDebug` still fails - suggesting the task doesn't use this configuration for its javac classpath.

**Workarounds Attempted (All Failed)**

| Attempt | Result |
|---------|--------|
| Add `hilt-android` to `ksp()` | No effect - KSP processor config, not javac |
| Add to `hiltCompileOnly*` configurations | Dependency resolves but task still fails |
| Add to `annotationProcessor*` configurations | No effect |
| Modify task classpath via `afterEvaluate { tasks.matching { it.name.startsWith("hiltJavaCompile") }.configureEach { classpath = ... } }` | AGP 9.0 configuration resolution errors |

**Task Registration Details**

The `hiltJavaCompile{Variant}` task appears to be registered by the Hilt Gradle plugin with its own classpath configuration that doesn't include `hilt-android`. The task dependencies show:

```
Registered task dependencies: app:freeDebugCompileClasspath
Registered task dependencies: app:kotlinCompilerPluginClasspathFreeDebug
```

But the actual javac invocation doesn't seem to use the full `freeDebugCompileClasspath`.

**Potential Fix Location**

Based on the task naming (`hiltJavaCompile*`) and the configurations created (`hiltCompileOnly*`, `hiltAnnotationProcessor*`), the fix likely needs to be in the Hilt Gradle plugin where it registers the `HiltJavaCompileTask` - it should include `hilt-android` (or at least the classes.jar from the AAR) on the javac classpath.

Looking at the Dagger source, this might be in `HiltGradlePlugin.kt` or wherever `hiltJavaCompile` tasks are configured.

**Environment**

- AGP: 9.0.0
- Gradle: 9.3.0  
- Kotlin: 2.2.10
- KSP: 2.2.10-2.0.2
- Hilt: 2.59 (failing), 2.58 (works)
- macOS, Java 21

**Why Hilt 2.58 Works**

Hilt 2.58's Gradle plugin doesn't generate `@ComponentTreeDeps` or `@ProcessedRootSentinel` annotated code - these annotations are only used in the AGP 9.0 support added in 2.59.

**Current Workaround**

Staying on Hilt 2.58 with AGP 9.0 - works fine despite lacking official AGP 9.0 support.

**Comment by daduz-r** [comment]
I might be hitting a similar issue with Hilt 2.59:

```
error: cannot find symbol
import dagger.hilt.internal.processedrootsentinel.ProcessedRootSentinel;
```

The project also failed to compile for me with Hilt 2.57.2 and 2.58.

For context, I’m using Kotlin 2.2.21, Gradle 9.0 and KSP 2.3.4.

I was able to get the project compiling after removing the following lines from gradle.properties, although I’m not certain this is the root cause:

```
android.nonFinalResIds=false
android.enableJetifier=true
```

I hope this can help you with the resolution.

**Comment by bcorso** [comment]
@paragbaxi, thanks for the analysis.

I'm actually concerned about this part:

> **Why Hilt 2.58 Works**
>
> Hilt 2.58's Gradle plugin doesn't generate @ComponentTreeDeps or @ProcessedRootSentinel annotated code - these annotations are only used in the AGP 9.0 support added in 2.59.

It suggests something strange is going on because the `@ComponentTreeDeps` and `@ProcessedRootSentinel` should be generated in both version. It's what triggers the generation of the actual Dagger components, so if that never happens something should break.

Also, I'm suprised Hilt 2.58 even works with AGP 9 (unless you have also set `android.newDsl=false`) because some of the APIs we were using are removed in AGP 9.

Would you be able to create a minimal reproducible example project that demonstrates this behavior?

**Comment by SerggioZS** [comment]
I have the same problem in my project using Hilt 2.59 and Gradle 9.
Downgraded to 2.58 and it works!

**Comment by bcorso** [comment]
@SerggioZS can you clarify which version of AGP you are using? Also, are you using Gradle 9.0/9.1/9.2? IIUC, AGP 9 requires Gradle 9.1+.

**Comment by SerggioZS** [comment]
@bcorso 

gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-9.1.0-bin.zip

root build.gradle
buildscript {

    ext.kotlin_version = '2.3.0'

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.0.0'
        classpath 'com.google.gms:google-services:4.4.4'
        classpath 'com.google.android.gms:oss-licenses-plugin:0.10.10'
        classpath "com.google.dagger:hilt-android-gradle-plugin:2.58"
    }
}
plugins {
    id 'com.google.devtools.ksp' version '2.3.4' apply false
    id("org.jetbrains.kotlin.plugin.compose") version "$kotlin_version" apply false
    id("com.google.firebase.appdistribution") version "5.2.0" apply false
}

**Comment by bcorso** [comment]
Thanks for the info @SerggioZS.

If someone can create a minimal repro project for this issue that would be great.

**Comment by memostark** [comment]
I had the same compilation issue and I can confirm that removing `android.enableJetifier=true` from `gradle.properties` fixed it.

**Comment by SerggioZS** [comment]
@memostark Can confirm. Disable jetifier from gradle.properties `android.enableJetifier=false` and the project compiles with Hilt 2.59.
@bcorso You can simply create a new empty project setup Hilt dependencies and set `android.enableJetifier=true`

**Comment by paragbaxi** [comment]
**Confirmed: Disabling Jetifier fixes Hilt 2.59**

Following up on my detailed investigation above - @memostark and @SerggioZS were right. Disabling Jetifier resolves the issue completely.

```properties
# gradle.properties
android.enableJetifier=false
```

**Environment:**
- AGP: 9.0.0
- Gradle: 9.3.0
- Kotlin: 2.2.10
- KSP: 2.2.10-2.0.2
- Hilt: 2.59 ✅ (now working)

**Root Cause Hypothesis:**

Jetifier rewrites bytecode to convert legacy Android Support Library references to AndroidX. With Hilt 2.59's new AGP 9.0 support, the `hiltJavaCompile` task generates code that imports from `dagger.hilt.internal.*`. Jetifier appears to be interfering with how these classes are resolved from `hilt-android.aar`, causing javac to fail with "cannot find symbol" despite the classes existing in the AAR.

This explains why my earlier investigation showed the annotations were present in `classes.jar` but javac couldn't see them - Jetifier was corrupting the classpath resolution.

**Recommendation:**

For projects with `minSdk >= 21`, Jetifier is unnecessary overhead since all modern dependencies are AndroidX-native. Consider documenting this in the Hilt release notes as a known issue for users who still have `enableJetifier=true`.

Thanks @memostark and @SerggioZS for identifying the workaround! 🙏

**Comment by ccodega** [comment]
I cannot disable jetifier, do you have any plan for a proper fix?

**Comment by bcorso** [comment]
Thanks @memostark and @SerggioZS for the workaround and thanks @paragbaxi for confirming it works!

I've updated the [Dagger 2.59](https://github.com/google/dagger/releases/tag/dagger-2.59) release notes to mention this.

> I cannot disable jetifier, do you have any plan for a proper fix?

In order to get a proper fix we would need to better understand why enabling the jetifier results in classes missing from the class path (it certainly doesn't seem like it should). IMO, this sounds like a bug in AGP. 

Unfortunately, this flag is also deprecated in AGP 9 and will be completely removed in AGP 10 so I'm not sure how willing they would be to look into this.

**Comment by ccodega** [comment]
@bcorso I see the point but this will force apps using support library to migrate also for Hilt dependency, AGP upgrade to v10 I don't think it will be a strict requirement in the short term

**Comment by bcorso** [comment]
I'll definitely bring this up with the AGP team and report back if there's an update.

**Comment by hungvietnguyen** [comment]
Hi, I'm from the AGP team.

This issue might be related to this commit in AGP 9.0: https://android.googlesource.com/platform/tools/base/+/a001f18775064ead339d05afbdee9aa68e69e156.

Can you try setting `android.experimental.enableIdentityTransformsForProcessedArtifacts=true` in `gradle.properties` (which reverts to the behavior before that commit) and see if it helps?

**Comment by ccodega** [comment]
@hungvietnguyen unfortunately it doesn't help my side, I'm still having the same error

**Comment by hungvietnguyen** [comment]
@ccodega I see, could you attach a small example project?

**Comment by ccodega** [comment]
@hungvietnguyen here it is: https://github.com/ccodega/hilt_sample

**Comment by hungvietnguyen** [comment]
Thanks a lot for the project!

### Root cause

The root cause is that Hilt is not able to find `classes.jar` inside an AAR to put on the classpath of `hiltJavaCompile$variant` tasks when Jetifier is enabled. Hilt sets up the classpath by querying for artifact type `jar` ([this code](https://github.com/google/dagger/blob/9354ef3db3e35b2d486fc5836cc233b6d6197255/java/dagger/hilt/android/plugin/main/src/main/kotlin/dagger/hilt/android/plugin/HiltGradlePlugin.kt#L114-L132)).
  - When Jetifier is disabled, AGP has the following transforms: `aar` -> `extracted-aar` -> `jar` (this is `classes.jar` unzipped from the AAR) -> `android-classes-jar` -> `android-classes`. Because `jar` appears in this flow, when Hilt queries for `jar`, it will get `classes.jar` inside the AAR.
  - When Jetifier is enabled, AGP has the following transforms: `aar` -> `processed-aar` (`processed-aar` means the AAR is jetified) -> `extracted-aar` -> `processed-jar` -> `android-classes-jar` -> `android-classes`. Because `jar` does not appear in this flow, when Hilt queries for `jar`, it will NOT get `classes.jar` inside the AAR.

Adding the following snippet to the sample project and run `./gradlew :app:hiltJavaCompileDebug -Pandroid.enableJetifier=true` will demonstrate the issue:
```
androidComponents {
    onVariants { variant ->
        tasks.withType<JavaCompile>().matching { it.name == "hiltJavaCompile${variant.name.capitalized()}" }.configureEach {
            doFirst {
                println("This task is: $name")
                println("The current classpath is:\n${(this as JavaCompile).classpath.files.joinToString("\n")}")
                println("The (roughly) expected classpath is:\n${variant.compileClasspath.files.joinToString("\n")}")
            }
        }
    }
}
```

### Fix

A quick fix might be for Hilt to query for `android-classes-jar` or `android-classes` instead of `jar`.

The proper fix is probably to use [Component.compileClasspath](https://developer.android.com/reference/tools/gradle-api/9.0/com/android/build/api/variant/Component#compileClasspath()).

**Comment by bcorso** [comment]
@hungvietnguyen thanks for looking into this!

> A quick fix might be for Hilt to query for `android-classes-jar` or `android-classes` instead of `jar`.

Interestingly, we _were_ using `android-classes` previously but we removed it in [ea570e7](https://github.com/google/dagger/commit/ea570e7a15ace17418aecd2e04e52cb2fde995be#diff-4d0c3d268a9c0d75c64fe466126d0e312cddbba81488aa00ac8e95f4ce4f1a52L121-L123) because it was causing an issue with new constraints in Gradle 9 ([#4847 (comment)](https://github.com/google/dagger/issues/4847#issuecomment-3144174393)).

Unfortunately, I think we're stuck because:

  1. We can't add `android-classes` in addition to `jar` since we'll get the same Gradle 9 issue in [#4847 (comment)](https://github.com/google/dagger/issues/4847#issuecomment-3144174393).
  2. We can't replace `jar` with `android-classes` since Java/Kotlin libraries also offer an artifact of type 'jar' and we'll miss those if we remove 'jar'.

@danysantiago is this your understanding as well?

> The proper fix is probably to use [Component.compileClasspath](http://go/android-dev/reference/tools/gradle-api/9.0/com/android/build/api/variant/Component#compileClasspath()).

Can you explain this suggestion a bit further?

**Comment by hungvietnguyen** [comment]
> We can't replace `jar` with `android-classes` since Java/Kotlin libraries also offer an artifact of type 'jar' and we'll miss those if we remove 'jar'.

AGP has transforms from `jar` to `android-classes` also for Java/Kotlin libraries, so I think that should still work.

> The proper fix is probably to use [Component.compileClasspath](http://go/android-dev/reference/tools/gradle-api/9.0/com/android/build/api/variant/Component#compileClasspath()).

AGP sets up the classpath for the `JavaCompile` task at [this code](https://cs.android.com/android-studio/platform/tools/base/+/b8dd6de5f3669a58310d027009707d68969e6930:build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/JavaCompileUtils.kt;l=98;bpv=1), which is an internal method that calls the public API [Component.compileClasspath](https://developer.android.com/reference/tools/gradle-api/9.0/com/android/build/api/variant/Component#compileClasspath()). So Hilt can probably do something similar? (The `variant.compileClasspath` in my code snippet above shows how to use this API.)

**Comment by bcorso** [comment]
> AGP has transforms from jar to android-classes also for Java/Kotlin libraries, so I think that should still work.

Oh, that's great! @trexem will look into this.

> AGP sets up the classpath for the JavaCompile task at [this code](https://cs.android.com/android-studio/platform/tools/base/+/b8dd6de5f3669a58310d027009707d68969e6930:build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/JavaCompileUtils.kt;l=98;bpv=1), which is an internal method that calls the public API [Component.compileClasspath](https://developer.android.com/reference/tools/gradle-api/9.0/com/android/build/api/variant/Component#compileClasspath()). So Hilt can probably do something similar? (The variant.compileClasspath in my code snippet above shows how to use this API.)

IIUC, I think we are already using the compile + runtime classpaths here:

https://github.com/google/dagger/blob/9354ef3db3e35b2d486fc5836cc233b6d6197255/java/dagger/hilt/android/plugin/main/src/main/kotlin/dagger/hilt/android/plugin/HiltGradlePlugin.kt#L189-L204

However, we rely on the transforms for filtering since Hilt only needs a subset of the classpaths, e.g. here

https://github.com/google/dagger/blob/9354ef3db3e35b2d486fc5836cc233b6d6197255/java/dagger/hilt/android/plugin/main/src/main/kotlin/dagger/hilt/android/plugin/HiltGradlePlugin.kt#L212

While using the full compile/runtime configurations (i.e. without the filtering) would likely work, I think it would bloat the input classpath for our task and affect things like incremental compilation.

However, let me know if I've misunderstood something.

**Comment by bcorso** [comment]
FYI, I plan on doing a 2.59.1 release early next week that should include this fix.

**Comment by bcorso** [comment]
@hungvietnguyen looks like switching from `jar` to `android-classes` (https://github.com/google/dagger/pull/5111/changes) caused a regression of the transformation chain issue I mentioned above (see https://github.com/google/dagger/issues/5116):

<details>
  <summary>Build logs (Click to expand)</summary>

```
* What went wrong:
Could not determine the dependencies of task ':feature:home:impl:hiltJavaCompileReleaseUnitTest'.
> Could not resolve all dependencies for configuration ':feature:home:impl:releaseUnitTestCompileClasspath'.
   > Found multiple transformation chains that produce a variant of 'project :feature:home:impl' with requested attributes:
       - artifactType 'jar-for-dagger'
       - com.android.build.api.attributes.AgpVersionAttr '9.0.0'
       - com.android.build.api.attributes.BuildTypeAttr 'release'
       - org.gradle.category 'library'
       - org.gradle.jvm.environment 'android'
       - org.gradle.usage 'java-api'
       - org.jetbrains.kotlin.platform.type 'androidJvm'
     Found the following transformation chains:
       - From configuration ':feature:home:impl:releaseApiElements' variant 'android-classes-jar':
           - With source attributes:
               - artifactType 'android-classes-jar'
               - com.android.build.api.attributes.AgpVersionAttr '9.0.0'
               - com.android.build.api.attributes.BuildTypeAttr 'release'
               - com.android.build.gradle.internal.attributes.VariantAttr 'release'
               - org.gradle.libraryelements 'jar'
               - org.gradle.usage 'java-api'
           - Candidate transformation chains:
               - Transformation chain: 'IdentityTransform' -> 'CopyTransform':
                   - 'IdentityTransform':
                       - Converts from attributes:
                           - artifactType 'android-classes-jar'
                       - To attributes:
                           - artifactType 'android-classes'
                   - 'CopyTransform':
                       - Converts from attributes:
                           - artifactType 'android-classes'
                       - To attributes:
                           - artifactType 'jar-for-dagger'
       - From configuration ':feature:home:impl:releaseApiElements' variant 'jar':
           - With source attributes:
               - artifactType 'jar'
               - com.android.build.api.attributes.AgpVersionAttr '9.0.0'
               - com.android.build.api.attributes.BuildTypeAttr 'release'
               - com.android.build.gradle.internal.attributes.VariantAttr 'release'
               - org.gradle.libraryelements 'jar'
               - org.gradle.usage 'java-api'
           - Candidate transformation chains:
               - Transformation chain: 'UnzipTransform' -> 'CopyTransform':
                   - 'UnzipTransform':
                       - Converts from attributes:
                           - artifactType 'jar'
                       - To attributes:
                           - artifactType 'directory'
                   - 'CopyTransform':
                       - Converts from attributes:
                           - artifactType 'directory'
                       - To attributes:
                           - artifactType 'jar-for-dagger'
   > Found multiple transformation chains that produce a variant of 'project :core:ui' with requested attributes:
       - artifactType 'jar-for-dagger'
       - com.android.build.api.attributes.AgpVersionAttr '9.0.0'
       - com.android.build.api.attributes.BuildTypeAttr 'release'
       - org.gradle.category 'library'
       - org.gradle.jvm.environment 'android'
       - org.gradle.usage 'java-api'
       - org.jetbrains.kotlin.platform.type 'androidJvm'
     Found the following transformation chains:
       - From configuration ':core:ui:releaseApiElements' variant 'android-classes-jar':
           - With source attributes:
               - artifactType 'android-classes-jar'
               - com.android.build.api.attributes.AgpVersionAttr '9.0.0'
               - com.android.build.api.attributes.BuildTypeAttr 'release'
               - com.android.build.gradle.internal.attributes.VariantAttr 'release'
               - org.gradle.libraryelements 'jar'
               - org.gradle.usage 'java-api'
           - Candidate transformation chains:
               - Transformation chain: 'IdentityTransform' -> 'CopyTransform':
                   - 'IdentityTransform':
                       - Converts from attributes:
                           - artifactType 'android-classes-jar'
                       - To attributes:
                           - artifactType 'android-classes'
                   - 'CopyTransform':
                       - Converts from attributes:
                           - artifactType 'android-classes'
                       - To attributes:
                           - artifactType 'jar-for-dagger'
       - From configuration ':core:ui:releaseApiElements' variant 'jar':
           - With source attributes:
               - artifactType 'jar'
               - com.android.build.api.attributes.AgpVersionAttr '9.0.0'
               - com.android.build.api.attributes.BuildTypeAttr 'release'
               - com.android.build.gradle.internal.attributes.VariantAttr 'release'
               - org.gradle.libraryelements 'jar'
               - org.gradle.usage 'java-api'
           - Candidate transformation chains:
               - Transformation chain: 'UnzipTransform' -> 'CopyTransform':
                   - 'UnzipTransform':
                       - Converts from attributes:
                           - artifactType 'jar'
                       - To attributes:
                           - artifactType 'directory'
                   - 'CopyTransform':
                       - Converts from attributes:
                           - artifactType 'directory'
                       - To attributes:
                           - artifactType 'jar-for-dagger'
   > Found multiple transformation chains that produce a variant of 'project :core:ui' with requested attributes:
       - artifactType 'jar-for-dagger'
       - com.android.build.api.attributes.AgpVersionAttr '9.0.0'
       - com.android.build.api.attributes.BuildTypeAttr 'release'
       - org.gradle.category 'library'
       - org.gradle.jvm.environment 'android'
       - org.gradle.usage 'java-api'
       - org.jetbrains.kotlin.platform.type 'androidJvm'
     Found the following transformation chains:
       - From configuration ':core:ui:releaseTestFixturesApiElements' variant 'android-classes-jar':
           - With source attributes:
               - artifactType 'android-classes-jar'
               - com.android.build.api.attributes.AgpVersionAttr '9.0.0'
               - com.android.build.api.attributes.BuildTypeAttr 'release'
               - com.android.build.gradle.internal.attributes.VariantAttr 'release'
               - org.gradle.libraryelements 'jar'
               - org.gradle.usage 'java-api'
           - Candidate transformation chains:
               - Transformation chain: 'IdentityTransform' -> 'CopyTransform':
                   - 'IdentityTransform':
                       - Converts from attributes:
                           - artifactType 'android-classes-jar'
                       - To attributes:
                           - artifactType 'android-classes'
                   - 'CopyTransform':
                       - Converts from attributes:
                           - artifactType 'android-classes'
                       - To attributes:
                           - artifactType 'jar-for-dagger'
       - From configuration ':core:ui:releaseTestFixturesApiElements' variant 'jar':
           - With source attributes:
               - artifactType 'jar'
               - com.android.build.api.attributes.AgpVersionAttr '9.0.0'
               - com.android.build.api.attributes.BuildTypeAttr 'release'
               - com.android.build.gradle.internal.attributes.VariantAttr 'release'
               - org.gradle.libraryelements 'jar'
               - org.gradle.usage 'java-api'
           - Candidate transformation chains:
               - Transformation chain: 'UnzipTransform' -> 'CopyTransform':
                   - 'UnzipTransform':
                       - Converts from attributes:
                           - artifactType 'jar'
                       - To attributes:
                           - artifactType 'directory'
                   - 'CopyTransform':
                       - Converts from attributes:
                           - artifactType 'directory'
                       - To attributes:
                           - artifactType 'jar-for-dagger'

* Try:
> Remove one or more registered transforms, or add additional attributes to them to ensure only a single valid transformation chain exists.
> Run the :artifactTransforms report to see the available artifact transforms.
> Transformation failures are explained in more detail at https://docs.gradle.org/9.2.1/userguide/variant_model.html#sub:transform-ambiguity.
> Review the variant matching algorithm at https://docs.gradle.org/9.2.1/userguide/variant_attributes.html#sec:abm_algorithm.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
```
</details>

It's not clear how we should fix this. It seems like it's the exact same output just different transforms to get there, so I'm guessing which chain it chooses doesn't actually matter in this case. Is there any way to tell Gradle this? Any other suggestions?

**Comment by hungvietnguyen** [comment]
The error message says there are 2 transform chains that Gradle can't choose:
   1. `android-classes-jar` -> `android-classes` -> `jar-for-dagger`
   2. `jar` -> `directory` -> `jar-for-dagger`

(Each transform chain might handle the original jar differently, so Gradle can't just pick a random one.)

The first chain is expected. The second one is set up by Dagger and seems unnecessary because:
  - The JavaCompile task can work directly with jars, we don't need to unzip a `jar` to a `directory`.
  - `android-classes` already takes care of jars.

Maybe we can try removing the `UnzipTransform` from `jar` to `directory` and see if it helps?
