### ISSUE TITLE
NoClassDefFoundError: dagger/model/RequestKind after upgrade to 2.14.1

### ISSUE THREAD

**Issue by davido** [google/dagger#998]
After upgrade to `2.14.1` rules_closure doesn't seem to work: [1].

To reproduce, apply this rules_closure update PR and run: `bazel test javatests/...`. I tested it on Java 8 and Bazel 0.9.0rc3.

* [1] http://paste.openstack.org/show/629433

**Comment by davido** [comment]
Never mind. dagger-spi seems to be needed now as well:

```
$ wget https://repo1.maven.org/maven2/com/google/dagger/dagger-spi/2.14.1/dagger-spi-2.14.1.jar
dagger-spi-2.14.1.jar              100%[=============================================================>]  91.96K  --.-KB/s    in 0.07s

 unzip -t dagger-spi-2.14.1.jar | grep "dagger/model"
    testing: dagger/model/package-info.class   OK
    testing: dagger/model/Scope.class   OK
    testing: dagger/model/RequestKind.class   OK
    testing: dagger/model/Key.class   OK
    testing: dagger/model/Key$MultibindingContributionIdentifier.class   OK
    testing: dagger/model/Key$Builder.class   OK
    testing: dagger/model/AutoValue_Scope.class   OK
    testing: dagger/model/AutoValue_Key.class   OK
    testing: dagger/model/$AutoValue_Key.class   OK
    testing: dagger/model/$AutoValue_Key$Builder.class   OK
    testing: dagger/model/            OK
```
