### ISSUE TITLE
Migration from 2.7 to 2.8 - Subcomponent scopes

### ISSUE THREAD

**Issue by rafakob** [google/dagger#544]
I have a issue with subcomponent's scopes when I try to upgrade from 2.7 to 2.8.0.
Here's my architecture:

**Global App component**
```java
@PerApp
@Component(modules = {AppModule.class, DataModule.class, NetworkModule.class})
public interface AppComponent {
    ActivityComponent with(ActivityModule activityModule);
}
```

**Default Activity subcomponent**
```java
@PerActivity
@Subcomponent(modules = {ActivityModule.class})
public interface ActivityComponent {
    PinComponent with(PinModule pinModule);
    void inject(LoginActivity loginActivity);
    void inject(MainActivity mainActivity);
    //...
}
```

**Subcomponent for a specific activity**
```java
@PerActivity
@Subcomponent(modules = {PinModule.class})
public interface PinComponent {
    void inject(PinActivity pinActivity);
}

@Module
public class PinModule {
    //...
    @PerActivity
    @Provides
    PinItem provideMethods();
    //...
}
```

This structure works perfectly on 2.7, but on 2.8 it returns compilation error:
```
Error:(12, 8) error: [package.PinComponent] package.PinComponent has conflicting scopes:

package.ActivityComponent also has @package.PerActivity
```

If I'm understanding this correctly, I would have to provide a separate scope annotation for `PinComponent`?

**Comment by ronshapiro** [comment]
Thats correct. Starting in 2.8 we are validating scopes across
subcomponents correctly. In previous versions we failed to check for this.

**Comment by rafakob** [comment]
Thanks for the answer. I guess I will have to rethink my architecture now ;)

**Comment by Kiran89kumar** [comment]
@rafakob : Did you able to fix this?

**Comment by rafakob** [comment]
@Kiran89kumar I did, you have to create a seperate annotation for that component.

**Comment by ronshapiro** [comment]
Please discuss this on another forum, like stackoverflow, which is better suited for questions.
