### ISSUE TITLE
java.lang.NoSuchMethodError: 'void com.android.build.api.extension.AndroidComponentsExtension$DefaultImpls.androidTests$default(com.android.build.api.extension.AndroidComponentsExtension, com.android.build.api.extension.VariantSelector, kotlin.jvm.functions.Function1, int, java.lang.Object)'

### ISSUE THREAD

**Issue by ColtonIdle** [google/dagger#2631]
Studio Build: BB canary1 Version of Gradle Plugin: 7.1 alpha01 Version of Gradle: 7.0.2

I have a project that is updated and work with Arctic Fox beta01 and AGP 7.0 beta01.

I installed bumblebee and got the upgrade assistant. After hitting the accept button I can see in git that the diff is:

```
-         classpath("com.android.tools.build:gradle:7.0.0-beta01")
+         classpath("com.android.tools.build:gradle:7.1.0-alpha01")
```

For reference here are my hilt dependency declarations

```
        classpath("com.google.dagger:hilt-android-gradle-plugin:2.35.1")


and


    implementation("com.google.dagger:hilt-android:2.35.1")
    kapt("com.google.dagger:hilt-compiler:2.35.1")


and

    implementation("androidx.hilt:hilt-navigation-fragment:1.0.0")
    implementation("androidx.hilt:hilt-navigation:1.0.0")
```

When I hit clean or sync I get the following error:

```
Unable to find method ''void com.android.build.api.extension.AndroidComponentsExtension$DefaultImpls.androidTests$default(com.android.build.api.extension.AndroidComponentsExtension, com.android.build.api.extension.VariantSelector, kotlin.jvm.functions.Function1, int, java.lang.Object)''
'void com.android.build.api.extension.AndroidComponentsExtension$DefaultImpls.androidTests$default(com.android.build.api.extension.AndroidComponentsExtension, com.android.build.api.extension.VariantSelector, kotlin.jvm.functions.Function1, int, java.lang.Object)'

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

```
* Exception is:
java.lang.NoSuchMethodError: 'void com.android.build.api.extension.AndroidComponentsExtension$DefaultImpls.androidTests$default(com.android.build.api.extension.AndroidComponentsExtension, com.android.build.api.extension.VariantSelector, kotlin.jvm.functions.Function1, int, java.lang.Object)'
	at dagger.hilt.android.plugin.HiltGradlePlugin.configureTransformASM(HiltGradlePlugin.kt:239)
	at dagger.hilt.android.plugin.HiltGradlePlugin.configureHilt(HiltGradlePlugin.kt:79)
	at dagger.hilt.android.plugin.HiltGradlePlugin.access$configureHilt(HiltGradlePlugin.kt:50)
	at dagger.hilt.android.plugin.HiltGradlePlugin$apply$1.execute(HiltGradlePlugin.kt:57)
	at dagger.hilt.android.plugin.HiltGradlePlugin$apply$1.execute(HiltGradlePlugin.kt:50)
```

Originally filed here before I saw Hilt in the stacktrace: https://issuetracker.google.com/issues/188563075

**Comment by shakil807g** [comment]
Having same issue with 

AGP:
classpath "com.android.tools.build:gradle:7.1.0-alpha01"

**Comment by danysantiago** [comment]
This is a duplicate of https://github.com/google/dagger/issues/2618, its fixed but we haven't made a release, if you want to get unblock you can use snapshot versions of Hilt from https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/

**Comment by b95505017** [comment]
@danysantiago I tried snapshot but get this error:
```
MyApplication_ComponentTreeDeps.java:197: error: cannot find symbol
@ComponentTreeDeps(
 ^
  symbol: class ComponentTreeDeps
```

**Comment by danysantiago** [comment]
@b95505017 thats not good...  can you try only using the `HEAD-SNAPSHOT` version of the plugin and keep the rest of the dependencies as you had them?

I need to investigate why that symbol  is not found, when it is [here](https://github.com/google/dagger/blob/master/java/dagger/hilt/internal/componenttreedeps/ComponentTreeDeps.java)

**Comment by b95505017** [comment]
@danysantiago It works when only use snapshot of the plugin!

**Comment by ColtonIdle** [comment]
@b95505017 I'm new to "snapshots". Can you let me know how you got this working?

**Comment by SimonMarquis** [comment]
@ColtonIdle to use the snapshot version, add something like this to your buildsript

```kotlin
buildscript {
    repositories {
        /*...*/
        maven(url = "https://oss.sonatype.org/content/repositories/snapshots") {
            content {
                includeModule("com.google.dagger", "hilt-android-gradle-plugin")
            }
        }
    }
    dependencies {
        /*...*/
        classpath("com.google.dagger:hilt-android-gradle-plugin:HEAD-SNAPSHOT")
    }
}
```

**Comment by ColtonIdle** [comment]
Thank you @SimonMarquis that helped! Really appreciate it!

**Comment by gulabsagevadiya** [comment]
> @ColtonIdle to use the snapshot version, add something like this to your buildsript
> 
> ```kotlin
> buildscript {
>     repositories {
>         /*...*/
>         maven(url = "https://oss.sonatype.org/content/repositories/snapshots") {
>             content {
>                 includeModule("com.google.dagger", "hilt-android-gradle-plugin")
>             }
>         }
>     }
>     dependencies {
>         /*...*/
>         classpath("com.google.dagger:hilt-android-gradle-plugin:HEAD-SNAPSHOT")
>     }
> }
> ```

i got this error while using this 
A problem occurred evaluating root project 'ComposeTrailApp'.
> Could not set unknown property 'url' for repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

Any Idea what to do

**Comment by SimonMarquis** [comment]
@gulabsagevadiya you shouldn't have to rely on a snapshot version anymore since version 2.36 is released: https://github.com/google/dagger/issues/2634#issuecomment-848357196

**Comment by rock3r** [comment]
I'm having the same issue with AGP 7.0 b04, Gradle 7.1, Dagger 2.37 and [all dependencies](https://github.com/rock3r/bundel/blob/compose-beta09/gradle/libs.versions.toml) to their latest versions:

![image](https://user-images.githubusercontent.com/153802/122351769-c2f27380-cf4e-11eb-8adb-02cc5fa98b22.png)

**Comment by mwy3055** [comment]
@rock3r Well I had same problem, solved with AGP 7.1.0-alpha02, Gradle 7.0.2, and Hilt 2.37. Try to do so.

**Comment by danysantiago** [comment]
@rock3r, @mwy3055, @slavonnet you are likely seeing a 'reencarnacion' of this issue, see: https://github.com/google/dagger/issues/2700

**Comment by olala2288** [comment]
I have the same issue, I don't know why google changes these crucial dependencies every time with no backward compatibility so we should spend hours to fix these.

**Comment by rafsanahmad** [comment]
I resolved the issue with: 
In project.gradle
        `classpath 'com.android.tools.build:gradle:7.0.4'
        classpath "com.google.dagger:hilt-android-gradle-plugin:2.38.1"`
In Build.gradle
    `implementation "com.google.dagger:hilt-android:2.38.1"
    kapt "com.google.dagger:hilt-android-compiler:2.38.1"`

**Comment by danielandrioli** [comment]
Goddamn, I spend some hours trying to fix this issue.

@rafsanahmad answer worked for me, finally. Thanks, man!
I'm using now Hilt's 2.38.1 version. The only difference is I'm using 7.1.1 for Gradle.

**Comment by arjun-sharma-acn** [comment]
@rafsanahmad  Thank you for ur answer....

**Comment by P3t3rP3r3z** [comment]
@rafsanahmad solution worked for me! thanks! also used @danielandrioli  advice and used 7.1.1 gradle
