### ISSUE TITLE
Jetpack Compose: Wrapping NavHost with Scaffold breaks Robolectric UI test

### ISSUE THREAD

**Issue by andre-krueger** [google/dagger#3261]
When running the test in `ExampleUnitTest`, this error is returned:
`Given component holder class com.example.app.MainActivity does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager
java.lang.IllegalStateException: Given component holder class com.example.app.MainActivity does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager
`

It seems that wrapping `NavHost` with `Scaffold` breaks the view model creation via  `hiltViewModel()`.
When I removed the Scaffold or wrap it around the `App` function inside `composable` it works.
This only happens when running the test, the app works correctly on a device or emulator, regardless if Scaffold is used or not.

Reproduction [App.zip](https://github.com/google/dagger/files/8097338/App.zip)

**Comment by kuanyingchou** [comment]
Thanks for reporting. There was an issue in AGP 7.1.0 and 7.1.1 that no bytecode transformation is done in unit tests(https://issuetracker.google.com/issues/213534628). Updating AGP to 7.1.2 should solve this.

**Comment by andre-krueger** [comment]
Can confirm that this works after updating AGP to 7.1.2 and adding the HiltAndroidRule.
Thank you!
