### ISSUE TITLE
[KSP] Missing `value class` in generics support for bindings

### ISSUE THREAD

**Issue by VincentMasselis** [google/dagger#4096]
I used to work with kapt, I recently switched to 2.48.x with KSP which fired some issue on my build, thanks to your efforts 2 of them were fixed with recent releases.

Now I'm facing a new one, I suppose the new KSP compiler doesn't support `value class` when used with generics because I'm creating a binding which uses a `UShort` as one of the generics but the created `.java` class from KSP replaces the type `UShort` by the classic `Short`.
There is the exception:
```
error: incompatible types: ColumnAdapter<Short,Long> cannot be converted to ColumnAdapter<UShort,Long>
    return Preconditions.checkNotNullFromProvides(Module.INSTANCE.database(driver, uuidAdapter, sensorLocationAdapter, pressureAdapter, temperatureAdapter, uShortAdapter));
```

You can consult the complete code used on [my repo here](https://github.com/VincentMasselis/TPMS-advanced/tree/chore/dagger-ksp-migration)
The binding which [fails here](https://github.com/VincentMasselis/TPMS-advanced/blob/f9477d791116bb4271d0045593e7642457c2f36f/data/vehicle/src/main/kotlin/com/masselis/tpmsadvanced/data/vehicle/ioc/Module.kt#L55)
And an example of a [failed github action build](https://github.com/VincentMasselis/TPMS-advanced/actions/runs/6500447753).

If your confident enough, you can directly try to build the app by yourself by fetching [the sources](https://github.com/VincentMasselis/TPMS-advanced/tree/chore/dagger-ksp-migration) and by simply running a `./gradlew bundleDemo` or any command you consider useful in this case, no environnement variable or plugin is required to run gradle command on this repo.

**Comment by kuanyingchou** [comment]
Hi, @VincentMasselis , thanks for reporting. I can reproduce it on my side. This looks like something we should fix as it was working with kapt. I'll look into this.

**Comment by kuanyingchou** [comment]
Hi, @VincentMasselis , this should be fixed now. Could you give HEAD-SNAPSHOT a try?

**Comment by VincentMasselis** [comment]
Hello @kuanyingchou [build](https://github.com/VincentMasselis/TPMS-advanced/actions/runs/6575805467) seems to be OK ! I'll will try to run on my phone to check if it run as excepted

**Comment by VincentMasselis** [comment]
Okay, I've run the app on my phone, everything works fine ! Thanks !

**Comment by mobilekosmos** [comment]
Any release date where this fix is coming?

**Comment by bcorso** [comment]
We're preparing for a release now. It may come out today if we get it done in time, otherwise it'll be out early next week.
