### ISSUE TITLE
Unable to generate TestComponent after update to 2.21+

### ISSUE THREAD

**Issue by zayo** [google/dagger#1599]
Hello, I find very strange behaviour when updating our android project to use incremental powers.

We use structure like this:
**/core/src/main/com/pckg/core/Provisions.kt**
```
interface Provisions {
    ....
}
```
**/app/src/main/com/pckg/AppComponent.kt**
```
@Component(modules=[....])
@Singleton
interface AppComponent : Provisions {
    ....
}
```
**/app/src/test/com/pckg/TestAppComponent.kt**
```
@Component(modules=[....])
@Singleton
interface TestAppComponent : AppComponent {
    ....
}
```

By practices on dagger.dev, those should be completely ok for UnitTesting. But for some unknown reason, the kapt fails to generate TestAppComponent.

Moreover, there is no direct error pointing to some issue:
```
> Task :app:kaptAppDebugUnitTestKotlin FAILED
/app/build/tmp/kapt3/stubs/appDebugUnitTest/com/pckg/TestAppComponent.java:77: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public abstract class TestAppComponent extends com.pckg.AppComponent {
                ^warning: The following options were not recognized by any processor: '[room.schemaLocation, kapt.kotlin.generated, room.incremental]'[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: android.databinding.annotationprocessor.ProcessDataBinding (DYNAMIC).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptAppDebugUnitTestKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

I tried almost everything. Even make AppComponent simple interface and define @Component in :app/main and :app/test, and depend on plain interface. But the same issue occurs.
I seriously don't believe, there is an circular dependency, as the regular app buildable.
Btw, except AppComponent, we have also PreInitComponent, that is also overriden in tests and it's generated. But it doesn't have any Provisions thing, can this be an issue?

So, do you have any idea, what else could I try? Or how to debug dagger/kapt to understand what is going on?

PS: I also write it on SO, if you want to answer also there: https://stackoverflow.com/questions/57657524/dagger-2-21-unable-to-generate-unittest-component-in-android

**Comment by zayo** [comment]
Hello again, could someone from @dagger team help me, please?

It's been a few months since I started investigating this and since then I have no results. All my theories was wrong. Unfortunately I'm not able to go over generated classes to "check" where the issue is as our project is has over 1000 of generated classes.

I'm not sure about anything. I just need to know, how to get more than `circular dependency` thing (which btw has nothing to do with dagger, it's from some basic AnnotationProcessor from auto, nothing to do with circular dependency).

Thanks

**Comment by Chang-Eric** [comment]
Hey, sorry for missing this earlier. So the circular dependency error usually means that we were trying to wait for all the symbols to be resolved, but it never happened. The typical way for a symbol to be resolved is for a code generator to kick in. For example, if you have your @Component extend a generated interface, then we need to wait a round of processing for that interface to be generated by someone else. If that interface never actually gets generated, then we would fail with this error. This logic of deferring generation comes from BasicAnnotationProcessor. It can happen with generated modules too.

I really wish BasicAnnotationProcessor had a way for us to pass information back to it on what was missing so we could make that error message better. Right now my guess on the best way to get information is you could see what was missing by throwing a break point into TypeCheckingProcessingStep in Dagger.

**Comment by zayo** [comment]
Hi,
thanks for reply. I tried to debug the TypeCheckingProcessingStep. Although it looked like a way, it was not.
It started with exception: 
`java.lang.TypeNotPresentException: Type mScannerTaskFactory not present`
The strange thing is, that this was reported for TestAppComponent, which is pure interface, so there is no field like that. I tried to change all `mScannerTaskFactory` usages names to detect what was the origin. It was from completely different class. Which is probably ok, as far as resolution of @component is depending on resolution of all parent dependencies. In our case:

```
class AppComponent {
    fun inject(service: Service)
}

class Service {
    @Inject
    lateinit var factory
}
```
So this would explain why the resolution of TestAppComponent which depends on AppComponent is failing.
Then it crossed my mind, that this Factory must be the issue. Guess what, it's not generated. We have only dagger and room, except that, nothing is generated. 

But still, I'm able to build whole AppComponent and run the app. So why would TestAppComponent failed if it's depending on the something that is for sure generated (otherwise the kapt would fail on AppComponent).

I tried the hotfix solution, to comment the mScannerTaskFactory's @Inject, but then I received another unresolved field from completely different class. After few commentings I gave up. This was completely random. If it would be generic problem of visiblity of classes (btw I tried also remove all internal modifier from our code, make everything public) then it would fail on resolution of every @Inject annotated field, not randomly picking classes and field.

So, it's a mystery for me.
Is anything from what I wrote rings a bell?

**Comment by Chang-Eric** [comment]
Hm, that does seem very strange. This doesn't ring any bells for me. When you catch the TypeNotPresentException, can you capture the stacktrace and add it here? It may help to know what Dagger was trying to do when it failed.

**Comment by zayo** [comment]
Hi, my coworker found the issue today.

It's due to conflict with FindBugs.
We have defined FB as:
```
    compileOnly "com.google.code.findbugs:annotations:3.0.1"
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
```

This dependency is for some reason not propagated to the unit tests.
So if we have a class with suppress:
```
public class JavaClass {
    @Inject
    @SuppressFBWarnings(value = "THIS_CRASHES_DAGGER",
            justification = "Since this annotation is not available in test classpath, dagger will fail.")
    Context mInjectedContext;
}
```
The `@SuppressFBWarnings` is not available in tests. This was ok up to dagger 2.20. But every version after is failing on that with the strange exception I mentioned earlier.

The fix is easy:
```
    testCompileOnly "com.google.code.findbugs:annotations:3.0.1"
    testCompileOnly "com.google.code.findbugs:jsr305:3.0.2"
```

But I'm still not sure, if this is correct behaviour. We don't run FindBugs on UnitTest classes, so we don't need that annotation. But since it's not stripped dagger fails on that.

Is this intended behaviour? I would expect, dagger will not fail on unknown/unresolved annotation if it's not his business, right?

I made a minimal example that shows the error. Can be fixed by adding the dependencies, or removing the FB Suppress annotation.
Just run `./gradlew testDebugUnitTest`
[DaggerExample.zip](https://github.com/google/dagger/files/3819162/DaggerExample.zip)

**Comment by Chang-Eric** [comment]
I'm not sure what change was put in between then but in general we do need to look at other annotations to see if they are an @Qualifier or even some other type of annotation in case of a misconfiguration. For example, we may check if you accidentally placed a scope annotation in a wrong place to try to warn you about it.

Thanks for the repro, I will try to find some time later to look through it.

**Comment by Chang-Eric** [comment]
I think to make the error messages better we'd need to do a deeper rewrite of stuff. This is related to some other bugs, so I put that into #2208 and am going to close this bug out.
