### ISSUE TITLE
AssistedInject sometimes fails to generate factory if the annotated factory interface extends another factory interface

### ISSUE THREAD

**Issue by arkivanov** [google/dagger#5032]
Kotlin:  2.1.21
Dagger: 2.56.2
[Anvil-KSP](https://github.com/zacsweers/anvil): 0.4.1
KSP: 2.1.20-2.0.1

In an `api` module:

```kotlin
interface Foo {

    interface Factory {
        fun create(dependency: Dependency): Foo
    }
}
```

In an `impl` module:

```kotlin
class FooImpl @AssistedInject constructor(
    @Assisted dependency: Dependency,
)  : Foo {

    @ContributesBinding(AppScope::class)
    @AssistedFactory
    interface Factory : Foo.Factory {
        override fun create(dependency: Dependency): FooImpl
    }
}
```

Then somewhere in the code:

```
@SingleIn(AppScope:class)
class MyThing @Inject constructor(
    fooFactory:  Foo.Factory,
)
```

This code always compiles and works locally. But the `kspReleaseKotlin` task often fails on CI. There are 2 possible errors, and the same build might pass when restarted.

Possible failure 1:

```
* What went wrong:
Execution failed for task ':app:kspReleaseKotlin'.
> A failure occurred while executing com.google.devtools.ksp.gradle.KspAAWorkerAction
   > expected one element but was: <create, create>
```

Possible failure 2:

```
e: [ksp] [com.example.Foo.Factory.create(com.example.Dependency)] Invalid return type: com.example.Foo. An assisted factory's abstract method must return a type with an @AssistedInject-annotated constructor.
e: [ksp] The @AssistedFactory-annotated type should contain a single abstract, non-default method but found multiple: [com.example.Foo.Factory.create(com.example.Dependency), com.example.FooImpl.Factory.create(com.example.Dependency)]
```

I think this started to happen after we updated Kotlin from 2.0.21 to 2.1.20, Dagger from 2.52 to 2.56.2 and KSP from 2.0.21-1.0.26 to 2.1.20-2.0.1.

**Comment by bcorso** [comment]
@arkivanov I have a feeling this is due to KSP. Is there any way you could keep all of the other dependencies the same and revert the KSP dependency back to 2.021-1.026? If that doesn't work, can you repeat the process for all of the dependencies you changed independently to narrow down exactly which dependency caused the change?

**Comment by arkivanov** [comment]
Thank you. I tried downgrading KSP but build fails with:

```
> Task :...:kspKotlin FAILED
e: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.config.LanguageVersionSettings org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$Companion.getLANGUAGE_VERSION_SETTINGS_DEFAULT()'
        at com.google.devtools.ksp.processing.impl.ResolverImpl.<init>(ResolverImpl.kt:147)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:225)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:75)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze$lambda$7(KotlinToJVMBytecodeCompiler.kt:326)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:317)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.runFrontendAndGenerateIrUsingClassicFrontend(KotlinToJVMBytecodeCompiler.kt:154)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:75)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:36)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:113)
        at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.kt:337)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1700)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

I tried to dig Dagger code a bit, added some logs and published internally, and I noticed the following:

1. `AssistedInjectionAnnotations#assistedFactoryMethods` sometimes gets two methods instead of one, in case there is a Factory interface extending another Factory interface and overriding its `create` method without body (abstract). The one method is from the actual Factory interface (annotated with `@AssistedFactory`), and another method from the super Factory interface.
2. When <span>#</span>1 happens, checking `XMethodElement#overrides` erroneously returns false.
3. I tried to filter out super `create` methods in `AssistedInjectionAnnotations#assistedFactoryMethods` but then it was failing for the same reason after Anvil merged Dagger Components. Because it also follows the same pattern: a generated Component Factory interface extends our manually written Component Factory interface and overrides its `create` method.
4. <span>#</span>3 was happening because `XProcessingEnvs#javacOverrides` was calling `XMethodElement#overrides` (see <span>#</span>2). Then I patched `XProcessingEnvs#javacOverrides` to also filter out super methods, but then we had random build failures because of missing bindings.

Hope this helps. Let me know if you need any help from my side.

**Comment by bcorso** [comment]
Yeah, this has been reported before (https://github.com/google/dagger/issues/3450#issuecomment-3108716712) unfortunately, we were never able to get a consistent repro.

AFAICT, this is an issue with KSP (or maybe the kotlin compiler's analysis API) as `XMethod#overrides()` just calls into KSP's [`Resolver#overrides()`](https://github.com/google/ksp/blob/main/api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt#L128-L135) method.

For example, in the error below the Foo.Factory.create method should have been filtered out but since KSP's overrides method returns false we don't filter it and get both methds:

```
e: [ksp] The @AssistedFactory-annotated type should contain a single abstract, non-default method but found multiple: 
[
    com.example.Foo.Factory.create(com.example.Dependency), 
    com.example.FooImpl.Factory.create(com.example.Dependency)
]
```

> This code always compiles and works locally. But the kspReleaseKotlin task often fails on CI. There are 2 possible errors, and the same build might pass when restarted.

The main reason I never filed a bug with KSP with #3450 was because we could never figure out why it doesn't fail locally but only fails on CI. Without being able to reproduce locally it's difficult for us or KSP team to debug this further. Do you have any ideas on why it only fails on CI?

If you can repro this in a small project we could send it over to the KSP team to look into.

**Comment by arkivanov** [comment]
We are able to reproduce it locally, but with additional changes. The main changes are versions bumps:

AGP: 8.7.3 -> 8.13.0
android.experimental.lint.version Gradle property: 8.11.0 -> 8.13.0
com.android.tools.lint dependencies: 31.2.0 -> 31.13.0
Gradle wrapper: 8.9 -> 8.13

I can try creating a minimal reproducer, but I'm not sure if it will work.

**Comment by bcorso** [comment]
@arkivanov this has been a tricky issue to pin down for a while now. If you can manage to create a minimal reproducer that would greatly improve our ability to debug and fix this issue.
