### ISSUE TITLE
Incremental build failures with 2.25.2 (new Kotlin qualifier annotations)

### ISSUE THREAD

**Issue by GrahamBorland** [google/dagger#1659]
Seeing this frequently with incremental builds since updating to 2.25.2. Works fine on a clean build.

```
/path/to/AppComponent.java:78: error: [Dagger/MissingBinding] android.net.Uri cannot be provided without an @Provides-annotated method.
public interface AppComponent extends AndroidInjector<App>{
       ^
      android.net.Uri is injected at
          ynab.app.web.WebViewActivity.serverUrl
```

Here's the relevant parts of the component (Java):

```java
public interface AppComponent extends AndroidInjector<App>{

    // lots of other stuff

    @Component.Builder
    interface Builder {

        // lots of other stuff

        @BindsInstance Builder serverUrl(@Named("ServerUrl") Uri serverUrl);

    }
}
```

The error only happens since updating Dagger to 2.25.2 and changing the injection site to benefit from the new Kotlin support.

### BEFORE - always worked fine

```kotlin
@Inject @field:Named("ServerUrl") internal lateinit var serverUrl: Uri
```
### AFTER updating to 2.25.2 - regular incremental build failures
```kotlin
@Inject @Named("ServerUrl") internal lateinit var serverUrl: Uri
```

If I have misunderstood what's supposed to be possible with 646e0336cdbe454baa5fe73c0af11f211a92deeb then I look forward to being educated. :)

Dagger 2.25.2
Kotlin 1.3.50
Android Gradle Plugin 3.5.1

**Comment by danysantiago** [comment]
Thanks for reporting this! We are aware of some cases where Dagger is still unable to find the qualifier annotation, meaning you have to fallback to `@field:Named`.

I was able to reproduce the issue in a small project with two gradle modules. App and Lib. Where Lib has the Kotlin class being member injected and App is where Dagger is setup with `kapt`. The issue is that Dagger is failing to find the synthetic method where property annotations are placed when the class being inspected is not from source, i.e. its already compiled.

We are still working on a fix but at the same time I filled a bug towards `kapt` with regards to the stub inconsistency: https://youtrack.jetbrains.com/issue/KT-34684

**Comment by danysantiago** [comment]
Yes - It might be possible that this is also observed during incremental builds.

**Comment by GuilhE** [comment]
@GrahamBorland why not switching from `@Named `to `@Qualifier`?

Example:
 ```
@Qualifier
@Retention(AnnotationRetention.RUNTIME)
annotation class ServerDateFormat

@Qualifier
@Retention(AnnotationRetention.RUNTIME)
annotation class CalendarPickerDateFormat


@Provides
@Singleton
@ServerDateFormat
fun provideServerDateFormat(): SimpleDateFormat {
    return SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ", Locale.getDefault())
}

@Provides
@Singleton
@CalendarPickerDateFormat
fun provideCalendarPickerDateFormat(): SimpleDateFormat {
    return SimpleDateFormat("dd/MMM/yyyy", Locale.getDefault())
}
```

Not as a workaround but as an improvement.

**Comment by gildor** [comment]
@GuilhE This issue reproducible and for `@Named` and for `@Qualifier`, so no difference. 

> as an improvement

It's improvement only if you do not use this dependency between modules, sometimes you just cannot access annotation without creating a separate module for it which is overkill in many cases

**Comment by GuilhE** [comment]
@gildor thanks for sharing this knowledge, never had to use `@Qualifiers` between modules, only in the provider class and ViewModels/Classes.

**Comment by chrisjenx** [comment]
I just noticed this where we are running kapt on a library -> app module style setup.
