### ISSUE TITLE
error: InjectProcessingStep was unable to process 'AppModule(android.content.Context)' because 'AuthTokenDataManagerImpl' could not be resolved.

### ISSUE THREAD

**Issue by sivabe35** [google/dagger#3393]
Build successful in Android studio but not in gitlab pipeline failed with following message.

Daggerversion: 2.41
Kotlin : 1.6.21
compileOptions - Java11
build:gradle:7.2

```

error: InjectProcessingStep was unable to process 'AppModule(android.content.Context)' because 'AuthTokenDataManagerImpl' could not be resolved.
  
  Dependency trace:
      => element (CLASS): com.core.di.module.AppModule
      => element (METHOD): providesAuthTokenDataManager(AuthTokenDataManagerImpl)
      => type (EXECUTABLE method): (AuthTokenDataManagerImpl)com.core.data.datamanager.AuthTokenDataManager
      => type (ERROR parameter type): AuthTokenDataManagerImpl
  
  If type 'AuthTokenDataManagerImpl' is a generated type, check above for compilation errors that may have prevented the type from being generated. Otherwise, ensure that type 'AuthTokenDataManagerImpl' is on your classpath.
error: ModuleProcessingStep was unable to process 'com.core.di.module.AppModule' because 'AuthTokenDataManagerImpl' could not be resolved.
  
  Dependency trace:
      => element (CLASS): com.core.di.module.AppModule
      => element (METHOD): providesAuthTokenDataManager(AuthTokenDataManagerImpl)
      => type (EXECUTABLE method): (AuthTokenDataManagerImpl)com.core.data.datamanager.AuthTokenDataManager
      => type (ERROR parameter type): AuthTokenDataManagerImpl
  
  If type 'AuthTokenDataManagerImpl' is a generated type, check above for compilation errors that may have prevented the type from being generated. Otherwise, ensure that type 'AuthTokenDataManagerImpl' is on your classpath.
error: ComponentProcessingStep was unable to process 'com.core.di.component.AppComponent' because 'AuthTokenDataManagerImpl' could not be resolved.
  
  Dependency trace:
      => element (CLASS): com.core.di.module.AppModule
      => element (METHOD): providesAuthTokenDataManager(AuthTokenDataManagerImpl)
      => type (EXECUTABLE method): (AuthTokenDataManagerImpl)com.core.data.datamanager.AuthTokenDataManager
      => type (ERROR parameter type): AuthTokenDataManagerImpl
  
  If type 'AuthTokenDataManagerImpl' is a generated type, check above for compilation errors that may have prevented the type from being generated. Otherwise, ensure that type 'AuthTokenDataManagerImpl' is on your classpath.
```

**Comment by danysantiago** [comment]
If it builds locally but not in your CI then it seems related to the environment. Can you please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by abd3lraouf** [comment]
@danysantiago I got similar issue today, and it seems like we need to keep activities and fragments in proguard files especially when we are releasing from CI

**Comment by Chang-Eric** [comment]
Closing this for now since we need more information. https://github.com/google/dagger/issues/3386 seems to be the issue for https://github.com/google/dagger/issues/3393#issuecomment-1124974384.

**Comment by PhongHuynh93** [comment]
For me, the build failed in AS when I upgrade kotlin to 1.7.0 and hilt to 2.41

**Comment by NitroG42** [comment]
I got the issue too, but I'm unable to replicate it on a minimal sample (happening on a big private multi module project). I was kinda lost until I "think" I fixed it by renaming the package of the classes I got the error because it contained a case -> vehicleLock => renamed into vehiclelock.
If it happens again I'll try to investigate further but I couldn't find any logic behind that (the generated code was throwing an "symbol not found" on an existing class)
