### ISSUE TITLE
Upgrading to 2.20 prompts an error "not a framework type"

### ISSUE THREAD

**Issue by 15115464469** [google/dagger#1383]
@ContributesAndroidInjector
 abstract TestActivity testActivity();
 @ContributesAndroidInjector
 abstract TestFragment testFragment();

error: TestActivity is not a framework type |  
error: TestFragment is not a framework type |  

错误: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. |  
-- | --

**Comment by TonyTangAndroid** [comment]
This issue is highly rooted from AndroidX rather than Dagger. I have managed to stably reproduce this issue with this repository.



@ronshapiro

**Comment by ronshapiro** [comment]
I don't see where you're turning on jetifier/androidx - can you point me in that direction?

**Comment by TonyTangAndroid** [comment]
Sorry about the misunderstanding. The  _jetifier/androidx_  code is under branch [androidx_2_20](https://github.com/TonyTangAndroid/Dagger2Bug1383/tree/androidx_2_20).

**Comment by dmapr** [comment]
@TonyTangAndroid I think it might be a Jetifier problem. If you update to the Gradle plugin 3.3 (and Gradle 4.10.1) it builds and runs just fine, although I do think you should be using **AndroidSupportInjectionModule** instead of **AndroidInjectionModule** since you're using **AppCompatActivity**.

**Comment by TonyTangAndroid** [comment]
@15115464469 I have updated a [readme](https://github.com/TonyTangAndroid/Dagger2Bug1383) that summarizes the combination of Android X, Dagger and Android Gradle Plugin, which might be of assistance in resolving your problem.

**Comment by 15115464469** [comment]
> I don't see where you're turning on jetifier/androidx - can you point me in that direction?
The project root directory gradle.properties，now is working fine in Android Studio 3.3 with gradle 4.10.1

**Comment by 15115464469** [comment]
> @15115464469 I have updated a [readme](https://github.com/TonyTangAndroid/Dagger2Bug1383) that summarizes the combination of Android X, Dagger and Android Gradle Plugin, which might be of assistance in resolving your problem.

Thinks!

**Comment by 15115464469** [comment]
> I don't see where you're turning on jetifier/androidx - can you point me in that direction?

The project root directory gradle.properties，now is working fine in Android Studio 3.3 with gradle 4.10.1.

**Comment by jega-ms** [comment]
Just for reference. i had the same problem. It was Jetifier issue. please upgrade your gradle build tools plugin to 3.3.0

        classpath 'com.android.tools.build:gradle:3.3.0' 

Sample code: https://github.com/jega-ms/android-dagger2-mvp-rx
