### PR TITLE
Remove unnecessary `MembersInjectors.injectMembers` method

### PR DESCRIPTION
**Pull request by szymenpl**
~~The last use of the `MembersInjectors` class was removed in [this](https://github.com/google/dagger/commit/e05f921812772eba98ef3b4a1ab6b301f3b25e26#diff-fd8cd7984835e64dceea55e5b84f303cL257) commit, so it isn't used now during code generation.
 (This class is still used in `TypeNames` as a class name constant, which is no longer necessary)~~

Static `MembersInjectors.injectMembers` is no longer used during code generation.

### CODE REVIEW

File: java/dagger/internal/MembersInjectors.java [hunk 1]
```diff
@@ -1,65 +0,0 @@
...
-  }
-
-  /**
-   * Returns a {@link MembersInjector} implementation that injects no members
-   *
-   * <p>Note that there is no verification that the type being injected does not have {@link Inject}
-   * members, so care should be taken to ensure appropriate use.
-   */
-  @SuppressWarnings("unchecked")
-  public static <T> MembersInjector<T> noOp() {
```
Comment (ronshapiro) [inline java/dagger/internal/MembersInjectors.java]: We may not have a test for it, but this is returned when for types that have no injected members:

```java
class A {
  @Inject A() {}
}

@Component
interface C {
  MembersInjector<A> aMembersInjector();
}
```

File: java/dagger/internal/MembersInjectors.java [hunk 2]
```diff
@@ -1,65 +0,0 @@
...
-
-  private static enum NoOpMembersInjector implements MembersInjector<Object> {
-    INSTANCE;
-
-    @Override public void injectMembers(Object instance) {
-      checkInstanceNotNull(instance);
-    }
-  }
-
-  public static void checkInstanceNotNull(Object instance) {
```
Comment (ronshapiro) [inline java/dagger/internal/MembersInjectors.java]: This is use above, but we can make it probably

File: java/dagger/internal/codegen/TypeNames.java [hunk 3]
```diff
@@ -79,7 +78,6 @@
   static final ClassName MAP_PRODUCER = ClassName.get(MapProducer.class);
   static final ClassName MAP_PROVIDER_FACTORY = ClassName.get(MapProviderFactory.class);
   static final ClassName MEMBERS_INJECTOR = ClassName.get(MembersInjector.class);
-  static final ClassName MEMBERS_INJECTORS = ClassName.get(MembersInjectors.class);
```
Comment (ronshapiro) [inline java/dagger/internal/codegen/TypeNames.java]: See `MemberSelect.noOpMembersInjector()`

Comment (szymenpl) [reply java/dagger/internal/codegen/TypeNames.java]: Ok, right. 
So can I remove static `injectMembers` from `MembersInjectors`. It's seems to be not used.

File: java/dagger/internal/MembersInjectors.java [hunk 4]
```diff
@@ -57,7 +48,7 @@
     }
   }
 
-  public static void checkInstanceNotNull(Object instance) {
+  private static void checkInstanceNotNull(Object instance) {
     checkNotNull(instance, "Cannot inject members into a null reference");
```
Comment (ronshapiro) [inline java/dagger/internal/MembersInjectors.java]: Maybe just inline this above?

**Comment by ronshapiro** [comment]
Great, thanks! We'll submit this internally and then sync a commit with your authorship here!

**Comment by Tagakov** [comment]
Hi, I am using a dependency which is built with old version of dagger. After updating to `2.14.1` I am facing crash when dependency mentioned above references to MembersInjectors.injectMembers which is not presented in current version anymore.

Exception description
`java.lang.NoSuchMethodError: No static method injectMembers(Ldagger/MembersInjector;Ljava/lang/Object;)`

Generated code from library
```java
public OverlayPresenter get() {
    return (OverlayPresenter)MembersInjectors.injectMembers(this.overlayPresenterMembersInjector, new OverlayPresenter((PresenterConfiguration)this.presenterConfigurationProvider.get(), (BusinessInteractor)this.businessInteractorProvider.get()));
}
```

I am not sure how to fix it, can you help please?

**Comment by ronshapiro** [comment]
You should shade the `dagger.internal` from one (or both) of the libraries. The old one is probably easiest

**Comment by vovkab** [comment]
Any reason we did breaking changes to a "public" api?
It is not really internal if it is end up being used by client code, even if it is autogenerated.

**Comment by JakeWharton** [comment]
Strongly disagree. The nature of generated code is such that many things
have visibilities beyond what you'd otherwise desire in order to facilitate
the functionality.

Perhaps an annotation and error-prone check can enforce true public API for
@Generated code.

**Comment by ronshapiro** [comment]
It's a good idea to be shading any `dagger.internal.*` code if you're sharing it with other libraries that are being compiled separately/that you can't guarantee are being compiled at the same dagger version.

**Comment by vovkab** [comment]
@JakeWharton That is all ok if you have access to code to generate.

If you are building a library using dagger, all code generation is already done. So we either should not change "public" api to keep it compatible, or we should do real client code generation to make sure there is no dagger dependencies left to worry about, i.e. internals should not be on a class path, generate anything you may need in clients namespace.

**Comment by tbroyer** [comment]
I have to agree with @vovkab here, if generated code depends on `dagger.internal.*` then `dagger.internal.*` is part of the public API. If your answer is "shade it", then it at least needs to be properly documented (and then people will re-evaluate their use of Dagger in libraries –like they did for Guava for a while, before the recent change in policy– as it'll consequently bloat their apps with duplicate shaded code; and/or we'll likely see "forks" of the `com.google.dagger:dagger` artifact only to retain backwards compatibility).

**Comment by elye** [comment]
I facing this issue as well

```
java.lang.NoSuchMethodError: No static method injectMembers(Ldagger/MembersInjector;Ljava/lang/Object;)
```

What does the `shade` in  `You should shade the dagger.internal from one (or both) of the libraries.` refers to?

**Comment by elye** [comment]
Thanks @tbroyer. I'm using gradle (Android Studio). 
From the reference, sound the `shading` referring to a process that's packaging the jar. 

What if I don't have control over the jar where I can't make changes to it, is there anything I could do?

P/S: I tried `exclude` as below so we could have a single dagger version used in my app, but it is not working

    implementation(group: "my.package", name: "lib-name, version: "$ver") {
        exclude group: 'com.google.dagger'
    }

Can I assume if the library uses the same dagger version as mine (e.g. both of us move to 2.19), then this would not be an issue?

**Comment by ronshapiro** [comment]
There's no guarantee that the generated code (i.e. factories) work well with each other across versions. We don't have any way of testing that. It's a generally good idea that any libraries that are intended to use Dagger in tandem are using the same version of Dagger.

If a library _you don't own_ is passing along Dagger codegen to you and isn't documenting it, that's a bad idea on the library owners part.

In fairness, we don't really have a good way to share libraries across project owners that guaranteed support across multiple versions.

**Comment by vovkab** [comment]
> There's no guarantee that the generated code (i.e. factories) work well with each other across versions. 

They don't have to be, this is pre-generated code, the problem is in code that ships in dagger jar.

> If a library you don't own is passing along Dagger codegen to you and isn't documenting it, that's a bad idea on the library owners part.

In my opinion, this really should not matter, this is an internal library code.

> In fairness, we don't really have a good way to share libraries across project owners that guaranteed support across multiple versions.

We actually do, here are a couple suggestions:
1. Everything that gets referenced from client code back to dagger jar is a public code and should remain backward compatible. (this is where the problem right now, we keep breaking "public" code and making minor versions incompatible with each other)
2. Or/and - generate standalone di code. Copy any utils or classes generated code requires, into client namespace or inline them. This way we could keep generated code independent from dagger library.

**Comment by vovkab** [comment]
This is still an issue, for example now even google is packaging dagger2 into their libraries without creating a shadowed version:

```
+--- com.google.firebase:firebase-crashlytics:17.0.0
|    +--- com.google.android.datatransport:transport-backend-cct:2.2.1
|    |    +--- com.google.android.datatransport:transport-runtime:2.2.1
|    |    |    +--- com.google.android.datatransport:transport-api:2.2.0
|    |    |    \--- com.google.dagger:dagger:2.27
```

What this means is that if dagger library again introduce breaking change like this one, we would be stuck with 2.27 until google decide to update dagger version. What makes it even worth is that other libraries may use different versions of dagger which would be incompatible between each other.
