### ISSUE TITLE
Koltlin 2.4.0

### ISSUE THREAD

**Issue by JuanPabloNarvaezPacheco** [google/dagger#5180]
Version 2.59.2 does not compile with the latest Kotlin 2.4.0

**Comment by mchauhan3-wooliesx** [comment]
Same here. When using Dagger 2.59.2 with KSP, an internal `@Provides` method in a Hilt module causes code generation to fail with:
``` 
e: [ksp] java.lang.IllegalArgumentException: Can't escape identifier `provideMyDependency$project_name:module_name_debug` because it contains illegal characters: :

**Comment by bcorso** [comment]
@mchauhan3-wooliesx thanks for providing the error message!

Note that this is failing in KSP not Dagger -- you can follow the KSP issue here: https://github.com/google/ksp/issues/2964.

This issue is due to a change in the module name in Kotlin 2.4.0:

https://kotlinlang.org/docs/whatsnew24.html#consistent-module-names-across-platforms

The above link also includes a workaround to rename your module name back to what it was previously:

**Comment by bcorso** [comment]
I'm going to close this issue since there's nothing for Dagger team to do here.

Please follow https://github.com/google/ksp/issues/2964 for the fix.

**Comment by Link184** [comment]
@bcorso I got another error after I upgraded to kotlin 2.4.0

```
Execution failed for task ':myApp:hiltJavaCompileDevelopmentDebug' (registered by plugin 'com.android.internal.application').
> Compilation failed; see the compiler output below.

error: [Hilt] Provided Metadata instance has version 2.4.0, while maximum supported version is 2.3.0. To support newer versions, update the kotlin-metadata-jvm library.: java.lang.IllegalArgumentException: Provided Metadata instance has version 2.4.0, while maximum supported version is 2.3.0. To support newer versions, update the kotlin-metadata-jvm library.
        at kotlin.metadata.jvm.internal.JvmReadUtils.throwIfNotCompatible$kotlin_metadata_jvm(JvmReadUtils.kt:95)
```

**Comment by bcorso** [comment]
@Link184 that issue should be fixed by https://github.com/google/dagger/pull/5179, but it won't be included until the next Dagger release (maybe next week).

In the meantime, you can manually bump the dependency in your own project (see the discussion in https://github.com/google/dagger/issues/5059, and and example here: https://github.com/EdricChan03/studybuddy-android/commit/04ebb1530fcd0c85e456bd1016376a6ae9039ac5).

You can also try out the [Dagger snapshot release](https://dagger.dev/dev-guide/versions) if you want to double check that the latest changes work for you.
