### ISSUE TITLE
Build fails due to unfound symbols in generated code that references objects wrapped in a sealed class

### ISSUE THREAD

**Issue by Nimrodda** [google/dagger#3429]
Dagger version: 4.42

We've been experiencing build failures due to unfound symbols in the generated code which is referencing a Kotlin object which is wrapped in a sealed class.

```
../../DaggerSomeComponent.java:123: error cannot find symbol 
import com.example.BeautySamplingToggle$FreeSamples;
                                                           ^
  symbol:   class BeautySamplingToggle$FreeSamples
  location: package com.example
  ```

**The object is a generic parameter of a provided dependency.**

After moving the objects outside the sealed class, the issue is resolved.

We started getting this issue after updating from Dagger version 2.40.5 to 2.42.

**Comment by bcorso** [comment]
Hi @Nimrodda, this sounds like a dupe of #3262. 

That bug should hopefully explain the issue and how to work around it.

FWIW, we considered relaxing this new constraint, but determined it wasn't really feasible due to https://github.com/google/dagger/issues/3262#issuecomment-1097446695.

**Comment by Nimrodda** [comment]
Here's a code snippet which is very close to the code we have that produces the issue:

```
sealed class Toggles {
    object First : FeatureToggleDefinition.DisabledByDefault("foo")
    object Second : FeatureToggleDefinition.EnabledByDefault("bar")
}

interface FeatureToggleDefinition {
    val id: String
    val defaultValue: Boolean

    abstract class DisabledByDefault(final override val id: String) : FeatureToggleDefinition {
        final override val defaultValue: Boolean get() = false
    }

    abstract class EnabledByDefault(final override val id: String) : FeatureToggleDefinition {
        final override val defaultValue: Boolean get() = true
    }
}

@Suppress("unused")
@JvmSuppressWildcards
fun interface FeatureToggleValueProvider<T : FeatureToggleDefinition> {
    fun isFeatureEnabled(): Boolean
}

@Suppress("unused")
fun <T : FeatureToggleDefinition> T.enabled() = FeatureToggleValueProvider<T> { true }

@Module
object ActivityModule {
    @Singleton
    @Provides
    internal fun provideFirstEnabled(
    ): FeatureToggleValueProvider<Toggles.First> {
        return Toggles.First.enabled()
    }

    @Singleton
    @Provides
    internal fun provideSecondEnabled(
    ): FeatureToggleValueProvider<Toggles.Second> {
        return Toggles.Second.enabled()
    }
}

@Singleton
@Component(modules = [
    ActivityModule::class,
])
interface ActivityComponent {
    fun inject(activity: MainActivity)

    @Component.Factory
    interface Factory {
        fun create(): ActivityComponent
    }
}

class MainActivity : AppCompatActivity() {
    @Inject
    lateinit var first: FeatureToggleValueProvider<Toggles.First>

    @Inject
    lateinit var second: FeatureToggleValueProvider<Toggles.Second>

    override fun onCreate(savedInstanceState: Bundle?) {
        DaggerActivityComponent.create().inject(this)
        super.onCreate(savedInstanceState)
    }
```

**Comment by bcorso** [comment]
Okay thanks, that does indeed sound different from https://github.com/google/dagger/issues/3262. 

I'll try to repro with your snippets, and get back to you once I find something.

**Comment by bcorso** [comment]
Sorry for the delay. I tried out the snippet in https://github.com/google/dagger/issues/3429#issuecomment-1156171610 using Dagger 2.42 but I was unable to reproduce the issue. @Nimrodda if you can provide more details on how to reproduce or provide a small example project reproducing the issue I'd be happy to take a further look.

**Comment by Nimrodda** [comment]
Thanks for looking into this issue. It's quite tricky to reproduce because this issue appears randomly also for us.
With that said, the issue is consistent everytime it happens: Dagger generates `$` instead of `.` for nested objects inside a sealed class.
