### ISSUE TITLE
Update "annotationProcessor "com.google.dagger:dagger-compiler: 2.12" to any version is getting an error

### ISSUE THREAD

**Issue by dfvalenciav** [google/dagger#3340]
When I am trying to update  "annotationProcessor "com.google.dagger:dagger-compiler: 2.12" to any version on android and go to build process I am getting an error saying that it is unable to find daggerAppComponent, and my project does not work

**Comment by dfvalenciav** [comment]
Hi @bcorso 
When i update annotationProcessor for instance to 2.40.3 and build the project the error is the next one : 

error: cannot find symbol 
symbol: class DaggerAppComponent

**Comment by bcorso** [comment]
> When i update annotationProcessor for instance to 2.40.3

Can you try 2.41? 2.40.X has some know issues.

> and build the project the error is the next one 
>
> error: cannot find symbol
> symbol: class DaggerAppComponent

There is very likely another error message that you are missing in your build logs.

If you're building from AndroidStudio's UI, it will sometimes only show part of the error message unless you click the right place to see the full build log. I would try to find that and search for other error messages.

If you're building from command line, can you post the entire build output (starting from where you initially run your command)?

**Comment by dfvalenciav** [comment]
I am building app via Android Studio UI.
I have  updated to 2.41. However the result is the same.
The error occurs when the task achieve Compiling with JDK Java complier API like it is unable to generate daggerAppComponent
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/8507885/162797351-06860efc-62e1-46c2-8620-b2e195204658.png">

**Comment by bcorso** [comment]
> The error occurs when the task achieve Compiling with JDK Java complier API like it is unable to generate daggerAppComponent

Yes, it sounds like the issue is that your `DaggerAppComponent` is unable to be generated, but it's impossible for me to tell you why without more information. If you can't find anything else in the error logs, you can try putting together a sample project that reproduces the issue and I can take a look.

**Comment by h908714124** [comment]
Have you tried `./gradlew clean` once?

**Comment by dfvalenciav** [comment]
I have use clean and delete build folder . However, the problem persists
The only thing that have worked partially is going into build folder and update files manually but it is a tedious and high time effort task
I cannot share repo due to confidence clauses.
Any other idea...
