### ISSUE TITLE
Update to 2.40.1 from 2.40 breaks build

### ISSUE THREAD

**Issue by DHosseiny** [google/dagger#3024]
I have a hilt @Entrypoint and other dagger components that depend on it and the code is working in 2.40 but not in 2.40.1.
Code example similar to my code:
In 1st Gradle module with hilt dependencies:

```
@EntryPoint
@InstallIn(SingletonComponent::class)
interface SomeComponent {

    fun exposeContext(): Context

    fun exposeApplication(): Application
}

```
In 2nd Gradle module with dagger dependencies(not hilt):

```
@CoreScope
@Component(
    modules = [
        CoreInjectionModule::class,
        AndroidInjectionModule::class,
        DatabaseModule::class,
        CoreViewModelModule::class,
        CoreServicesModule::class,
        CoreBroadcastModule::class,
        CoreWorkerModule::class
    ],
    dependencies = [GiantComponent::class, SomeComponent::class]
)
interface CoreComponent : ExposeCoreDependencies, ExposeComponent, WorkerComponent {

    @CoreInjector
    override fun dispatcher(): BaseModuleAndroidInjector<Any>

    @CoreInjector
    override fun workers(): WorkerProviders
}

```
(Because I am between a migration from dagger I can not use hilt in all Gradle modules)
The build has this error: CoreComponent can not resolve all of its dependencies or have cyclic dependency...
I fixed it by reversing the hilt and dagger to 2.40 for now.

**Comment by carlonzo** [comment]
same here. 2.40 to 2.40.1 we get a `error: dagger.internal.codegen.ComponentProcessor was unable to process 'packagename.OurComponent' because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.`

**Comment by bcorso** [comment]
Hi @DHosseiny,

Unfortunately, I wasn't able to reproduce your issue with the setup you described above. 

Would you be able to provide a sample project that reproduces your issue?

**Comment by bcorso** [comment]
@DHosseiny we've had a couple patch releases since 2.40.1. 

Can you verify if you're still having the same issue with the latest 2.40.4?

**Comment by gmazzo** [comment]
Facing the same here, with `2.40.5`. Switching back to `2.40.` "fixes" it. Is there any way you can improve this crypting message with any clue of its source? "Check for compilation errors or a circular dependency with generated code." is just not good enough to actually do some research except for try and error.

**Comment by bcorso** [comment]
@gmazzo, yeah we've been having plans to improve this error message for a while https://github.com/google/dagger/issues/2208.

Due to the increase in issues related to this, I've now started looking into fixing it. Hopefully, we'll have better error messages in the next Dagger release.

**Comment by DHosseiny** [comment]
> @DHosseiny we've had a couple patch releases since 2.40.1.
> 
> Can you verify if you're still having the same issue with the latest 2.40.4?

Yes we have this issue still in 2.40.5. sorry I couldn't create a sample project to reproduce this issue. I think it is not simple to reproduce it in a sample project.

**Comment by shrikanthkr** [comment]
@bcorso I have created a sample that reproduces the same error.
https://github.com/shrikanthkr/dagger-issue-sample.

This seems to be an issue with nested component dependencies.

cc: @Sripadmanabans @shangeethsivan

**Comment by bcorso** [comment]
@shrikanthkr thanks for the repo case!

I've tested our latest error messages on your example app using Dagger's [`HEAD-SNAPSHOT` version]() and it now gives the following error message:

```
> Task :network:kaptDebugKotlin FAILED
error: ComponentProcessingStep was unable to process 'com.example.network.NetworkComponent' because 'com.example.crypto.CryptoComponent' could not be resolved.
  
  Dependency trace:
      => element (INTERFACE): com.example.store.StoreComponent
      => annotation: @dagger.Component(dependencies = com.example.crypto.CryptoComponent.class)
      => annotation method: java.lang.Class<?>[] dependencies()
      => annotation value (ARRAY): value 'com.example.crypto.CryptoComponent.class' with expected type java.lang.Class<?>[]
      => annotation value (TYPE): value 'com.example.crypto.CryptoComponent' with expected type java.lang.Class<?>
      => type (ERROR annotation value type): com.example.crypto.CryptoComponent
  
  If type 'com.example.crypto.CryptoComponent' is a generated type, check above for compilation errors that may have prevented the type from being generated. Otherwise, ensure that type 'com.example.crypto.CryptoComponent' is on your classpath.
```

Which seems to indicate that `:network` does not have access to `com.example.crypto.CryptoComponent`. You should be able to fix this either by adding an explicit `implementation` dependency:

```
':network' -[implementaiton]-> ':crypto'
```
or by an implicit `api` dependency on `:crypto` through the `:store` library:

```
':store' -[api]-> ':crypto'
```

**Comment by shrikanthkr** [comment]
@bcorso is it now an explicit requirement to include nested dependencies? The above works with 2.40 without any changes.

**Comment by bcorso** [comment]
@shrikanthkr we require it for our validation but you should be able to disable it explicitly using the compiler option:  `-Adagger.validateTransitiveComponentDependencies=DISABLED`.

For example, with `kapt` you can disable it like this:

```groovy
kapt {
    arguments {
        arg('dagger.validateTransitiveComponentDependencies', 'DISABLED')
    }
}
```

**Comment by shrikanthkr** [comment]
Thank you so much @bcorso.

**Comment by DHosseiny** [comment]
if error messages are better now, I think it can be closed ya?

**Comment by bcorso** [comment]
Sounds good. Thanks for following up.
